$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-1.html data-rel=dialog data-ajax=false>अशरीरी सिद्ध भगवान</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-2.html data-rel=dialog data-ajax=false>आ गया... आ गया...</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-3.html data-rel=dialog data-ajax=false>आओ जिनमंदिर में आओ</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-4.html data-rel=dialog data-ajax=false>आज मैं महावीर जी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-5.html data-rel=dialog data-ajax=false>आज सी सुहानी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-6.html data-rel=dialog data-ajax=false>आज हम जिनराज</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-7.html data-rel=dialog data-ajax=false>आया कहां से</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-8.html data-rel=dialog data-ajax=false>आया तेरे दरबार में</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-9.html data-rel=dialog data-ajax=false>आये तेरे द्वार</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-10.html data-rel=dialog data-ajax=false>आयो आयो रे हमारो</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-11.html data-rel=dialog data-ajax=false>एक तुम्हीं आधार हो</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-12.html data-rel=dialog data-ajax=false>ओ जगत के शांति दाता</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-13.html data-rel=dialog data-ajax=false>कभी वीर बनके</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-14.html data-rel=dialog data-ajax=false>कर लो जिनवर का गुणगान</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-15.html data-rel=dialog data-ajax=false>करता हूं तुम्हारा सुमिरन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-16.html data-rel=dialog data-ajax=false>करुणा सागर भगवान</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-17.html data-rel=dialog data-ajax=false>केसरिया केसरिया</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-18.html data-rel=dialog data-ajax=false>कोई इत आओ जी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-19.html data-rel=dialog data-ajax=false>गा रे भैया</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-20.html data-rel=dialog data-ajax=false>गाएँ जी गाएँ आदिनाथ</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-21.html data-rel=dialog data-ajax=false>घडी घडी पल पल</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-22.html data-rel=dialog data-ajax=false>चंद्रानन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-23.html data-rel=dialog data-ajax=false>चरणों में आया हूं</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-24.html data-rel=dialog data-ajax=false>चवलेश्वर पारसनाथ</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-25.html data-rel=dialog data-ajax=false>चाह मुझे है दर्शन की</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-26.html data-rel=dialog data-ajax=false>छोटा सा मंदिर</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-27.html data-rel=dialog data-ajax=false>जगदानंदन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-28.html data-rel=dialog data-ajax=false>जब कोई नहीं आता मेरे बाबा</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-29.html data-rel=dialog data-ajax=false>जयवंतो जिनबिम्ब</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-30.html data-rel=dialog data-ajax=false>जिन ध्याना गुण गाना</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-31.html data-rel=dialog data-ajax=false>जिनवर आनन भान</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-32.html data-rel=dialog data-ajax=false>जिनवर दरबार तुम्हारा</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-33.html data-rel=dialog data-ajax=false>झीनी झीनी उडे रे</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-34.html data-rel=dialog data-ajax=false>तिहारे ध्यान की मूरत</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-35.html data-rel=dialog data-ajax=false>तुझे प्रभु वीर कहते हैं</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-36.html data-rel=dialog data-ajax=false>तुम जैसा मैं भी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-37.html data-rel=dialog data-ajax=false>तुमसे लागी लगन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-38.html data-rel=dialog data-ajax=false>तुम्हारे दर्श बिन स्वामी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-39.html data-rel=dialog data-ajax=false>तुम्ही हो ज्ञाता</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-40.html data-rel=dialog data-ajax=false>तू ज्ञान का सागर है</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-41.html data-rel=dialog data-ajax=false>तेरी शांत छवि</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-42.html data-rel=dialog data-ajax=false>तेरी शीतल शीतल मूरत</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-43.html data-rel=dialog data-ajax=false>तेरी सुंदर मूरत</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-44.html data-rel=dialog data-ajax=false>तेरे दर्शन से मेरा</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-45.html data-rel=dialog data-ajax=false>तोरी पल पल</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-46.html data-rel=dialog data-ajax=false>दरबार तुम्हारा मनहर है</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-47.html data-rel=dialog data-ajax=false>दिन रात स्वामी तेरे गीत</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-48.html data-rel=dialog data-ajax=false>देखो जी आदिश्वर स्वामी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-49.html data-rel=dialog data-ajax=false>धन्य धन्य आज घडी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-50.html data-rel=dialog data-ajax=false>नाथ तुम्हारी पूजा</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-51.html data-rel=dialog data-ajax=false>नाम तुम्हारा तारणहारा कब तेरा</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-52.html data-rel=dialog data-ajax=false>निरखत जिन चंद्रवदन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-53.html data-rel=dialog data-ajax=false>निरखी निरखी मनहर</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-54.html data-rel=dialog data-ajax=false>निरखो अंग अंग</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-55.html data-rel=dialog data-ajax=false>नेमि जिनेश्वर</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-56.html data-rel=dialog data-ajax=false>पंचपरम परमेष्ठी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-57.html data-rel=dialog data-ajax=false>पद्मासद्म</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-58.html data-rel=dialog data-ajax=false>पारस प्यारा लागो</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-59.html data-rel=dialog data-ajax=false>पारस प्रभु का दर्शन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-60.html data-rel=dialog data-ajax=false>प्रभु दर्शन कर जीवन की</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-61.html data-rel=dialog data-ajax=false>प्रभु हम सब का एक</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-62.html data-rel=dialog data-ajax=false>प्रभुजी अब ना भटकेंगे</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-63.html data-rel=dialog data-ajax=false>बाहुबली भगवान</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-64.html data-rel=dialog data-ajax=false>भटके हुए राही को</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-65.html data-rel=dialog data-ajax=false>भव भव रुले हैं</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-66.html data-rel=dialog data-ajax=false>भावना की चूनरी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-67.html data-rel=dialog data-ajax=false>मन भाये चित हुलसाये</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-68.html data-rel=dialog data-ajax=false>मनहर तेरी मूरतियाँ</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-69.html data-rel=dialog data-ajax=false>महाराजा स्वामी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-70.html data-rel=dialog data-ajax=false>महावीर स्वामी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-71.html data-rel=dialog data-ajax=false>मिलता है सच्चा सुख केवल</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-72.html data-rel=dialog data-ajax=false>मेरे मन मंदिर में आन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-73.html data-rel=dialog data-ajax=false>मेरे महावीर झूले पलना</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-74.html data-rel=dialog data-ajax=false>मेरे सर पर रख दो भगवन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-75.html data-rel=dialog data-ajax=false>मैं तेरे ढिंग आया रे</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-76.html data-rel=dialog data-ajax=false>म्हारा आदीश्वर जी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-77.html data-rel=dialog data-ajax=false>रंगमा रंगमा</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-78.html data-rel=dialog data-ajax=false>रोम रोम पुलकित हो जाये</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-79.html data-rel=dialog data-ajax=false>रोम रोम में नेमिकुंवर के</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-80.html data-rel=dialog data-ajax=false>रोम रोम से निकले</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-81.html data-rel=dialog data-ajax=false>वन्दों अद्भुत चन्द्रवीर जिन</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-82.html data-rel=dialog data-ajax=false>वर्तमान को वर्धमान की</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-83.html data-rel=dialog data-ajax=false>वर्धमान ललना से</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-84.html data-rel=dialog data-ajax=false>वीतरागी देव</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-85.html data-rel=dialog data-ajax=false>वीर प्रभु के ये बोल</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-86.html data-rel=dialog data-ajax=false>शुद्धात्मा का श्रद्धान</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-87.html data-rel=dialog data-ajax=false>शौरीपुर वाले</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-88.html data-rel=dialog data-ajax=false>श्री अरिहंत छवि लखिके</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-89.html data-rel=dialog data-ajax=false>श्री जिनवर पद ध्यावें जे नर</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-90.html data-rel=dialog data-ajax=false>सीमंधर स्वामी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-91.html data-rel=dialog data-ajax=false>सुरपति ले अपने शीश</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-92.html data-rel=dialog data-ajax=false>स्वामी तेरा मुखडा</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-93.html data-rel=dialog data-ajax=false>हम यही कामना करते हैं</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-94.html data-rel=dialog data-ajax=false>हरो पीर मेरी</a></li>');
  $('#bhajanListView-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-95.html data-rel=dialog data-ajax=false>हे प्रभो चरणों में</a></li>');
  $("\#bhajanListView-देव").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-1.html data-rel=dialog data-ajax=false>आज मैं परम पदारथ</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-2.html data-rel=dialog data-ajax=false>ओंकारमयी वाणी तेरी</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-3.html data-rel=dialog data-ajax=false>करता हूं मैं अभिनंदन</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-4.html data-rel=dialog data-ajax=false>चरणों में आ पडा हूं</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-5.html data-rel=dialog data-ajax=false>जब एक रत्न अनमोल</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-6.html data-rel=dialog data-ajax=false>जिनवाणी अमृत रसाल</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-7.html data-rel=dialog data-ajax=false>जिनवाणी की सुनै सो</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-8.html data-rel=dialog data-ajax=false>जिनवाणी जग मैया</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-9.html data-rel=dialog data-ajax=false>जिनवाणी माँ जिनवाणी माँ</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-10.html data-rel=dialog data-ajax=false>जिनवाणी माता दर्शन की</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-11.html data-rel=dialog data-ajax=false>जिनवाणी माता रत्नत्रय निधि</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-12.html data-rel=dialog data-ajax=false>जिनवैन सुनत, मोरी भूल भगी</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-13.html data-rel=dialog data-ajax=false>धन्य धन्य जिनवाणी माता शरण</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-14.html data-rel=dialog data-ajax=false>धन्य धन्य वीतराग वाणी</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-15.html data-rel=dialog data-ajax=false>महिमा है अगम</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-16.html data-rel=dialog data-ajax=false>माँ जिनवाणी तेरो नाम</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-17.html data-rel=dialog data-ajax=false>माँ जिनवाणी बसो हृदय में</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-18.html data-rel=dialog data-ajax=false>माता तू दया करके</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-19.html data-rel=dialog data-ajax=false>म्हारी माँ जिनवाणी</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-20.html data-rel=dialog data-ajax=false>ये शाश्वत सुख का प्याला</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-21.html data-rel=dialog data-ajax=false>शरण कोई नहीं जग में</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-22.html data-rel=dialog data-ajax=false>शांती सुधा बरसाये</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-23.html data-rel=dialog data-ajax=false>सांची तो गंगा</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-24.html data-rel=dialog data-ajax=false>सीमंधर मुख से</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-25.html data-rel=dialog data-ajax=false>सुनकर वाणी जिनवर की</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-26.html data-rel=dialog data-ajax=false>हे जिनवाणी माता तुमको लाखों प्रणाम</a></li>');
  $('#bhajanListView-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-27.html data-rel=dialog data-ajax=false>हे शारदे माँ</a></li>');
  $("\#bhajanListView-शास्त्र").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-1.html data-rel=dialog data-ajax=false>ऐसा योगी क्यों न अभयपद पावै</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-2.html data-rel=dialog data-ajax=false>ऐसे मुनिवर देखें</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-3.html data-rel=dialog data-ajax=false>ऐसे साधु सुगुरु कब मिलि हैं</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-4.html data-rel=dialog data-ajax=false>कबधौं मिलै मोहि श्रीगुरु</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-5.html data-rel=dialog data-ajax=false>गुरु रत्नत्रय के धारी</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-6.html data-rel=dialog data-ajax=false>धन धन जैनी साधु…</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-7.html data-rel=dialog data-ajax=false>धनि मुनि जिन यह</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-8.html data-rel=dialog data-ajax=false>धनि मुनि निज आतमहित कीना</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-9.html data-rel=dialog data-ajax=false>धन्य मुनिराज हमारे हैं</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-10.html data-rel=dialog data-ajax=false>धन्य मुनीश्वर आतम हित में</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-11.html data-rel=dialog data-ajax=false>नित उठ ध्याऊँ, गुण गाऊँ</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-12.html data-rel=dialog data-ajax=false>निर्ग्रंथों का मार्ग</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-13.html data-rel=dialog data-ajax=false>परम गुरु बरसत ज्ञान झरी</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-14.html data-rel=dialog data-ajax=false>परम दिगम्बर मुनिवर देखे</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-15.html data-rel=dialog data-ajax=false>परम दिगम्बर यती</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-16.html data-rel=dialog data-ajax=false>बधाई आज मिल गाओ</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-17.html data-rel=dialog data-ajax=false>मुनिवर आज मेरी कुटिया में</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-18.html data-rel=dialog data-ajax=false>मुनिवर को आहार</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-19.html data-rel=dialog data-ajax=false>म्हारा परम दिगम्बर मुनिवर आया</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-20.html data-rel=dialog data-ajax=false>वे मुनिवर कब मिली हैं उपगारी</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-21.html data-rel=dialog data-ajax=false>वेष दिगम्बर धार</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-22.html data-rel=dialog data-ajax=false>शान्ति सुधा बरसा गये</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-23.html data-rel=dialog data-ajax=false>शुद्धातम तत्व विलासी रे</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-24.html data-rel=dialog data-ajax=false>श्री मुनि राजत समता संग</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-25.html data-rel=dialog data-ajax=false>संत साधु बन के विचरूँ</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-26.html data-rel=dialog data-ajax=false>सिद्धों की श्रेणी में आने वाला</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-27.html data-rel=dialog data-ajax=false>है परम-दिगम्बर मुद्रा जिनकी</a></li>');
  $('#bhajanListView-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-28.html data-rel=dialog data-ajax=false>होली खेलें मुनिराज शिखर वन में</a></li>');
  $("\#bhajanListView-गुरु").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-1.html data-rel=dialog data-ajax=false>आजा अपने धर्म की तू राह में</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-2.html data-rel=dialog data-ajax=false>उठे सब के कदम</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-3.html data-rel=dialog data-ajax=false>जय जिनेन्द्र बोलिए</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-4.html data-rel=dialog data-ajax=false>जहाँ रागद्वेष से रहित निराकुल</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-5.html data-rel=dialog data-ajax=false>जैन धर्म के हीरे मोती</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-6.html data-rel=dialog data-ajax=false>बडे भाग्य से हमको मिला जिन धर्म</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-7.html data-rel=dialog data-ajax=false>भावों में सरलता रहती है</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-8.html data-rel=dialog data-ajax=false>मैं महापुण्य उदय से जिनधर्म</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-9.html data-rel=dialog data-ajax=false>ये धरम है आतम ज्ञानी का</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-10.html data-rel=dialog data-ajax=false>लहर लहर लहराये, केसरिया झंडा</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-11.html data-rel=dialog data-ajax=false>लहरायेगा-लहरायेगा झंडा</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-12.html data-rel=dialog data-ajax=false>श्रीजिनधर्म सदा जयवन्त</a></li>');
  $('#bhajanListView-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-13.html data-rel=dialog data-ajax=false>सब जैन धर्म की जय बोलो</a></li>');
  $("\#bhajanListView-धर्म").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-1.html data-rel=dialog data-ajax=false>ऊंचे ऊंचे शिखरों वाला 1</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-2.html data-rel=dialog data-ajax=false>ऊंचे ऊंचे शिखरों वाला 2</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-3.html data-rel=dialog data-ajax=false>ऊंचे शिखरों पे बसा है</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-4.html data-rel=dialog data-ajax=false>गगन मंडल में उड जाऊं</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-5.html data-rel=dialog data-ajax=false>चलो सब मिल सिधगिरी</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-6.html data-rel=dialog data-ajax=false>जीयरा...जीयरा...जीयरा</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-7.html data-rel=dialog data-ajax=false>मधुबन के मंदिरों में</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-8.html data-rel=dialog data-ajax=false>रे मन भज ले प्रभु का नाम</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-9.html data-rel=dialog data-ajax=false>विश्व तीर्थ बडा प्यारा</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-10.html data-rel=dialog data-ajax=false>सम्मेद शिखर पर मैं जाऊंगा</a></li>');
  $('#bhajanListView-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-11.html data-rel=dialog data-ajax=false>सांवरिया पारसनाथ शिखर पर</a></li>');
  $("\#bhajanListView-तीर्थ").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-1.html data-rel=dialog data-ajax=false>आज तो बधाई राजा नाभि</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-2.html data-rel=dialog data-ajax=false>आनंद अवसर आज सुरगण आये</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-3.html data-rel=dialog data-ajax=false>आया पंच कल्याणक महान</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-4.html data-rel=dialog data-ajax=false>कल्पद्रुम यह समवसरण है</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-5.html data-rel=dialog data-ajax=false>कुण्डलपुर में वीर हैं जन्मे</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-6.html data-rel=dialog data-ajax=false>कुण्डलपुर वाले कुण्डलपुर वाले वीरजी</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-7.html data-rel=dialog data-ajax=false>गर्भ कल्याणक आ गया</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-8.html data-rel=dialog data-ajax=false>गावो री बधाईयां</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-9.html data-rel=dialog data-ajax=false>गिरनारी पर तप कल्याणक</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-10.html data-rel=dialog data-ajax=false>घर घर आनंद छायो</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-11.html data-rel=dialog data-ajax=false>चन्द्रोज्वल अविकार स्वामी जी</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-12.html data-rel=dialog data-ajax=false>जनम लिया है महावीर ने</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-13.html data-rel=dialog data-ajax=false>झुलाय दइयो पलना</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-14.html data-rel=dialog data-ajax=false>तेरे पांच हुये कल्याण प्रभु</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-15.html data-rel=dialog data-ajax=false>दिन-आयो दिन-आयो</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-16.html data-rel=dialog data-ajax=false>दिव्य ध्वनि वीरा खिराई</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-17.html data-rel=dialog data-ajax=false>नाचे रे इन्दर देव</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-18.html data-rel=dialog data-ajax=false>पंखिड़ा तू उड़ के जाना स्वर्ग</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-19.html data-rel=dialog data-ajax=false>पंखिडा रे उड के आओ कुंड्लपुर में</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-20.html data-rel=dialog data-ajax=false>पंचकल्याण मनाओ मेरे साथी</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-21.html data-rel=dialog data-ajax=false>पालकी उठाने का हमें अधिकार है</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-22.html data-rel=dialog data-ajax=false>बाजे कुण्डलपुर में बधाई</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-23.html data-rel=dialog data-ajax=false>मणियों के पलने में स्वामी महावीर</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-24.html data-rel=dialog data-ajax=false>महावीरा झूले पलना</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-25.html data-rel=dialog data-ajax=false>मेरा पलने में</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-26.html data-rel=dialog data-ajax=false>ये महामहोत्सव पंच कल्याणक</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-27.html data-rel=dialog data-ajax=false>रोम रोम में नेमिकुंवर के</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-28.html data-rel=dialog data-ajax=false>लिया आज प्रभु जी ने जनम सखी</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-29.html data-rel=dialog data-ajax=false>लिया प्रभू अवतार जयजयकार</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-30.html data-rel=dialog data-ajax=false>लिया रिषभ देव अवतार</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-31.html data-rel=dialog data-ajax=false>विषयों की तृष्णा को छोड</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-32.html data-rel=dialog data-ajax=false>सुरपति ले अपने शीश</a></li>');
  $('#bhajanListView-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-33.html data-rel=dialog data-ajax=false>हो संसार लगने लगा अब</a></li>');
  $("\#bhajanListView-कल्याणक").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-1.html data-rel=dialog data-ajax=false>करना मन ध्यान महामंत्र</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-2.html data-rel=dialog data-ajax=false>जप जप रे नवकार मंत्र</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-3.html data-rel=dialog data-ajax=false>जय जय जय कार परमेष्ठी</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-4.html data-rel=dialog data-ajax=false>जो मंगल चार जगत में हैं</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-5.html data-rel=dialog data-ajax=false>णमोकार नाम का ये कौन मंत्र</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-6.html data-rel=dialog data-ajax=false>णमोकार मन्त्र को प्रणाम हो</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-7.html data-rel=dialog data-ajax=false>नमन हमारा अरिहंतों को</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-8.html data-rel=dialog data-ajax=false>पंच परम परमेष्ठी देखे</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-9.html data-rel=dialog data-ajax=false>बने जीवन का मेरा आधार रे</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-10.html data-rel=dialog data-ajax=false>मंत्र जपो नवकार मनुवा</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-11.html data-rel=dialog data-ajax=false>मंत्र नवकार हमें प्राणों से प्यारा</a></li>');
  $('#bhajanListView-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-12.html data-rel=dialog data-ajax=false>मंत्र नवकारा हृदय में धर</a></li>');
  $("\#bhajanListView-महामंत्र").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-1.html data-rel=dialog data-ajax=false>अपनी सुधि पाय आप</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-2.html data-rel=dialog data-ajax=false>अपनी सुधि भूल आप</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-3.html data-rel=dialog data-ajax=false>अपने में अपना परमातम</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-4.html data-rel=dialog data-ajax=false>अब गतियों में नाहीं रुलेंगे</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-5.html data-rel=dialog data-ajax=false>अब मेरे समकित सावन</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-6.html data-rel=dialog data-ajax=false>अरे जिया जग धोखे की टाटी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-7.html data-rel=dialog data-ajax=false>आओ रे आओ रे ज्ञानानंद की डगरिया</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-8.html data-rel=dialog data-ajax=false>आतम रूप अनूपम अद्भुत</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-9.html data-rel=dialog data-ajax=false>ऐसा मोही क्यों न अधोगति जावै</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-10.html data-rel=dialog data-ajax=false>ओ जीवड़ा तू थारी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-11.html data-rel=dialog data-ajax=false>और अबै न कुदेव सुहावै</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-12.html data-rel=dialog data-ajax=false>कबधौं सर पर धर डोलेगा</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-13.html data-rel=dialog data-ajax=false>कबै निरग्रंथ स्वरूप धरूंगा</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-14.html data-rel=dialog data-ajax=false>करलो आतम ज्ञान परमातम</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-15.html data-rel=dialog data-ajax=false>कहा मानले ओ मेरे भैया</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-16.html data-rel=dialog data-ajax=false>काहे पाप करे काहे छल</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-17.html data-rel=dialog data-ajax=false>कैसो सुंदर अवसर आयो है</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-18.html data-rel=dialog data-ajax=false>कोई लाख करे चतुराई</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-19.html data-rel=dialog data-ajax=false>क्यूं करे अभिमान जीवन</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-20.html data-rel=dialog data-ajax=false>गाडी खडी रे खडी रे तैयार</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-21.html data-rel=dialog data-ajax=false>चेतन अपनो रूप निहारो</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-22.html data-rel=dialog data-ajax=false>चेतन तूँ तिहुँ काल अकेला</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-23.html data-rel=dialog data-ajax=false>जब चले आत्माराम</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-24.html data-rel=dialog data-ajax=false>जिया कब तक उलझेगा</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-25.html data-rel=dialog data-ajax=false>जीव! तू भ्रमत सदैव अकेला</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-26.html data-rel=dialog data-ajax=false>जीवन के किसी भी पल में</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-27.html data-rel=dialog data-ajax=false>जैन धरम के हीरे मोती</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-28.html data-rel=dialog data-ajax=false>जो अपना नहीं उसके अपनेपन</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-29.html data-rel=dialog data-ajax=false>जो आज दिन है वो, कल ना रहेगा</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-30.html data-rel=dialog data-ajax=false>जो जो देखी वीतराग</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-31.html data-rel=dialog data-ajax=false>ज्ञाता दृष्टा राही हूं</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-32.html data-rel=dialog data-ajax=false>तन पिंजरे के अन्दर बैठा</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-33.html data-rel=dialog data-ajax=false>तू जाग रे चेतन देव तुझे जिनदेव</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-34.html data-rel=dialog data-ajax=false>तू जाग रे चेतन प्राणी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-35.html data-rel=dialog data-ajax=false>तोड़ विषियों से मन जोड़</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-36.html data-rel=dialog data-ajax=false>देखा जब अपने अंतर को</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-37.html data-rel=dialog data-ajax=false>धोली हो गई रे काली कामली</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-38.html data-rel=dialog data-ajax=false>ध्यान धर ले प्रभू को</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-39.html data-rel=dialog data-ajax=false>निजपुर में आज मची रे होरी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-40.html data-rel=dialog data-ajax=false>निजपुर में आज मची होरी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-41.html data-rel=dialog data-ajax=false>पाना नहीं जीवन को</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-42.html data-rel=dialog data-ajax=false>पाप मिटाता चल ओ बंधू</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-43.html data-rel=dialog data-ajax=false>भजन बिन योंही जनम गमायो</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-44.html data-rel=dialog data-ajax=false>भाया थारी बावली जवानी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-45.html data-rel=dialog data-ajax=false>भूल के अपना घर</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-46.html data-rel=dialog data-ajax=false>मन महल में दो दो भाव जगे</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-47.html data-rel=dialog data-ajax=false>ममता की पतवार ना तोडी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-48.html data-rel=dialog data-ajax=false>माया में फ़ंसे इंसान</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-49.html data-rel=dialog data-ajax=false>मेरे कब ह्वै वा दिन की सुघरी</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-50.html data-rel=dialog data-ajax=false>मैं ज्ञानानंद स्वभावी हूं</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-51.html data-rel=dialog data-ajax=false>मैं दर्शन ज्ञान स्वरूपी हूं</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-52.html data-rel=dialog data-ajax=false>मैं हूँ आतमराम</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-53.html data-rel=dialog data-ajax=false>मोक्ष पद मिलता है धीरे धीरे</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-54.html data-rel=dialog data-ajax=false>मोह की महिमा देखो</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-55.html data-rel=dialog data-ajax=false>मोहे भावे न भैया थारो देश</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-56.html data-rel=dialog data-ajax=false>ये शाश्वत सुख का प्याला</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-57.html data-rel=dialog data-ajax=false>वीर भज ले रे भाया</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-58.html data-rel=dialog data-ajax=false>शास्त्रों की बातों को मन</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-59.html data-rel=dialog data-ajax=false>संसार महा अघसागर</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-60.html data-rel=dialog data-ajax=false>सजधज के जिस दिन</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-61.html data-rel=dialog data-ajax=false>सिद्धों से मिलने का मार्ग</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-62.html data-rel=dialog data-ajax=false>सुन रे जिया चिरकाल गया</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-63.html data-rel=dialog data-ajax=false>सुनो जिया ये सतगुरु की बातैं</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-64.html data-rel=dialog data-ajax=false>सोते सोते ही निकल</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-65.html data-rel=dialog data-ajax=false>हम तो कबहुँ न निज घर आये</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-66.html data-rel=dialog data-ajax=false>हम तो कबहुँ न निजगुन भाये</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-67.html data-rel=dialog data-ajax=false>हम तो कबहूँ न हित उपजाये</a></li>');
  $('#bhajanListView-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-68.html data-rel=dialog data-ajax=false>हम न किसीके कोई न हमारा</a></li>');
  $("\#bhajanListView-अध्यात्म").listview('refresh');
})
