var relativePath="./";
var homePage="index.html";

function show_map(choice) {
  var abc;
  $(".bottomContainer").html("Wait a min please !!");
  if(choice=='KA') {
    abc='<table width=90% border=0><tr><td align=left><h4> <ol>'+
	'<li>HAL, Bangalore, Karnataka</li>'+
	'<li>Mysore, Karnataka - 152Kms<ul><li>Contact : </li></ul></li>'+
	'<li>Way to Kanakagiri, Kilalipura, Karnataka 571109 - 53Kms<ul><li>Contact : 08226-296786, 296809. Food, stay available</li></ul></li>'+
	'<li>Way to Gommatgiri Temple, Bettadur, Karnataka 571103 - 76Kms<ul><li>Contact : </li></ul></li>'+
	'<li>Shravanabelagola, Karnataka - 78Kms<ul><li>Contact : 08176-257258. Food, Stay available.</li></ul></li>'+
	'<li>Dharmasthala, Karnataka - 167Kms<ul><li>Contact : 08256277141. Stay available.</li></ul></li>'+
	'<li>Venoor, Karnataka - 33Kms<ul><li>Contact : </li></ul></li>'+
	'<li>Moodabidri, Karnataka - 20Kms<ul><li>Contact : 08258236418. Book your stay. North India food not available</li></ul></li>'+
	'<li>Karkala, Karnataka - 18Kms<ul><li>Contact : </li></ul></li>'+
	'<li>Varanga, Karnataka - 24kms<ul><li>Contact : </li></ul></li>'+
	'<li>Kundadri Hill - 43Kms <ul><li>Contact : 9482781142</li></ul></li>'+
	'<li>Sri Humcha Parasnath Jain Temple Humcha, Karnataka 577436 - 55Kms<ul><li>Contact : 08185262721/9481584316. Book your stay.</li></ul></li>'+
	'<li>Mandharagiri Hill - 310Kms <ul><li>Contact : 09964531836 Food facility available on call basis</li></ul></li>'+
	'<li>HAL, Bangalore, Karnataka - 74Kms</ol></td>'+
    '<td><iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=Hal,+New+Thippasandra,+Bangalore,+Karnataka,+India&amp;daddr=Mysore,+Karnataka,+India+to:Way+to+Kanakagiri,+Chamarajanagar,+Karnataka,+India+to:Way+to+Gommatgiri+Temple,+Bettadur,+Mysore,+Karnataka+571103,+India+to:Shravanabelagola,+Karnataka,+India+to:Dharmasthala,+Karnataka,+India+to:Venoor,+Karnataka,+India+to:Moodbidri,+Karnataka,+India+to:Karkal,+Karnataka,+India+to:Varanga,+Karnataka,+India+to:Kundadri+Hill+to:Sri+Humcha+Padmavathi+Devi+Jain+Temple,+Humcha,+Karnataka+577436,+India+to:Mandaragiri+Hill+to:Hal,+New+Thippasandra,+Bangalore,+Karnataka,+India&amp;hl=en-US&amp;geocode=FUDqxQAdcdigBCkHJJFtqhauOzFMHAC0GGsXLg%3BFYKeuwAdlGyRBCn5LlcdOHCvOzFtOfjA6OyJKw%3BFRhotgAdc16TBCkvOroKMEavOzGYHblZSClRvg%3BFaqyvAAdahuPBCnNIl_Z232vOzG_MEfFoxpMPw%3BFQUsxAAdbv2OBClXnUKbDfWvOzFQ5IMkXDkH_A%3BFXjBxQAduC5-BCkPHw3secikOzE3Mx6dcTNbFg%3BFROPxgAdHJF6BCmjUS0m4K2kOzGZt3m1q8Qc3Q%3BFf9pxwAdwE94BCmVdZCE5aqkOzFQWkyOQLDywA%3BFXylyQAd1Fl4BCnRIuliRVa7OzF0-UOzYsqIJA%3BFU1ezAAds354BClRei6HGV-7OzG0XwYiTO5cdA%3BFVHWzgAdav16BCnD_JIXs2i7OzE_Ogx5RugS6Q%3BFYyC0wAdnIx7BCEZq5UUC17ZyylJcoyLpp27OzEZq5UUC17Zyw%3BFUf-ygAdssaZBClvQf7aViuwOzEvjheaFeK4Pw%3BFUDqxQAdcdigBCkHJJFtqhauOzFMHAC0GGsXLg&amp;sll=13.09553,76.333008&amp;sspn=7.666591,13.392334&amp;gl=US&amp;mra=pd&amp;ie=UTF8&amp;t=m&amp;ll=12.978616,76.315792&amp;spn=2.066941,2.668474&amp;output=embed"></iframe></td></tr></table>';
  }else if(choice=='MP') {
    abc='<table width=90% border=0><tr><td align=left><h4>A=Lalitpur, Uttar Pradesh <br><br> B=Devgarh Hill Jain Temples Lalitpur, UP, Lalitpur Range, Uttar Pradesh 284403 - 34Kms <br><br> C=ThubonJi Digamber Jain Atishay Kshetra, Ashoknagar, Thobon, Madhya Pradesh 473446 - 86Kms <br><br> D=Khandargiri Jain Cave Temples Near Chanderi, AshokNagar, Chanderi, Madhya Pradesh 473446 - 17Kms <br><br> E=Laxman Mandir Chanderi, Madhya Pradesh 473446 - 4Kms <br><br> F=Paragarh Mandir Alampura, Madhya Pradesh 472339 - 105Kms <br><br> G=Papaura Ji Digamber Jain Kshetra National Highway 12A, Papaura, Madhya Pradesh 472001 - 13Kms <br><br> H=AharJi Digamber Atishay Kshetra Ahar Village, Tikamgarh, Ahar, Madhya Pradesh 472111 - 24Kms <br><br> I=Dronagiri Hill Jain Temples Sendhapa, Chhatarpur, Barma, Madhya Pradesh 471311 - 57Kms <br><br> J=Nainagiri Digamber Siddha Kshetra Nainagir, Dalpatpur, Manki, Madhya Pradesh 471318 - 77Kms <br><br> K=Kundalpur, Madhya Pradesh - 92Kms <br><br></td>'+
	'<td><iframe width=640 height=480 frameborder=0 scrolling=no marginheight=0 marginwidth=0 src="https://maps.google.com/maps?saddr=Lalitpur,+Uttar+Pradesh,+India&amp;daddr=Devgarh+Hill+Jain+Temples,+Lalitpur+Range,+Uttar+Pradesh,+India+to:ThubonJi+Digamber+Jain+Atishay+Kshetra,+Thobon,+Madhya+Pradesh,+India+to:Khandargiri+Jain+Cave+Temples,+Ramnagar,+Madhya+Pradesh,+India+to:Chanderi+jain+temple,+Madhya+Pradesh,+India+to:Paragarh+Mandir,+Alampura,+%E0%A4%AE%E0%A4%A7%E0%A5%8D%E0%A4%AF+%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%A6%E0%A5%87%E0%A4%B6,+%E0%A4%AD%E0%A4%BE%E0%A4%B0%E0%A4%A4+to:Papaura+Ji+Digamber+Jain+Kshetra,+Papaura,+Madhya+Pradesh,+India+to:AharJi+Digamber+Atishay+Kshetra,+Ahar,+Madhya+Pradesh,+India+to:Dronagiri+Hill+Jain+Temples,+Barma,+Madhya+Pradesh,+India+to:Nainagiri+Digamber+Siddha+Kshetra,+Manki,+Madhya+Pradesh,+India+to:Kundalpur,+Madhya+Pradesh,+India&amp;hl=en&amp;ie=UTF8&amp;sll=24.405514,78.863995&amp;sspn=1.793267,3.348083&amp;geocode=FX_AeAEdrIysBClvsaHlp7t5OTHXPQ8aGmAK7g%3BFfAcdgEdy--pBCEZ8rtorNTpnSnNxCAV3555OTEZ8rtorNTpnQ%3BFZtmeAEd1U2mBCHKJc-pzJ8d-SmBb-SGL4l5OTHKJc-pzJ8d-Q%3BFdPqeAEdMVmoBCH9xQMfTSo5oSlX6gzZk5F5OTH9xQMfTSo5oQ%3BFbEreQEd1DioBCGGZrSYejtB9CnRAGuAH5J5OTGGZrSYejtB9A%3BFRawegEdkvSyBCGJDv-JGZNHMCkbiiTof0h4OTGJDv-JGZNHMA%3BFZAMeQEdm0KzBCFGeq4u5TR-qimXijO0bUV4OTFGeq4u5TR-qg%3BFRR-eQEdWk21BCHMgmHZG_Hg-ynvubO1XkJ4OTHMgmHZG_Hg-w%3BFRV1dgEdMUO5BCG-2f6zFwOHZSlbGWMyn314OTG-2f6zFwOHZQ%3BFfBUcAEdYUG3BCF83vO3OrpKpinHoQ13A5Z4OTF83vO3OrpKpg%3BFUr7bQEdpG_ABCn39I-wHxiCOTHk7GIAAwZg_A&amp;oq=kundalpur&amp;mra=pr&amp;t=m&amp;ll=24.405514,78.863995&amp;spn=1.793267,3.348083&amp;output=embed"></iframe></td></tr></table>';
  }else if(choice=='TN') {
    abc='<table width=90% border=0><tr><td align=left><h4>A=Bangalore, Karnataka<br><br>B=Arihant Giri Digamabr Jain Temple Tiruvannamalai, Tamil Nadu 606907 - 248Kms<br><br>C=Arni, Tamil Nadu - 19Kms<br><br>D=Thiruppanamoor Ancient Digambar Jain Temple Thiruppanamoor, Tamil Nadu 604402 - 49Kms<br><br>E=Thiruparuthikundram Primary School Pillaiyarpalayam, Kanchipuram, Tamil Nadu 631502 - 19Kms<br><br>F=Arihant Giri Digamabr Jain Temple Tiruvannamalai, Tamil Nadu 606907 - 86 Kms<br><br>G=Ponnur Hill, Ponnur Malai, Vandavasi Taluk, Tiruvannamalai Dist, Vandavasi, Tamil Nadu 604505 - 47Kms<br><br>H=Birudur, Tamil Nadu - 13Kms<br><br>I=Nelliankulam, Tamil Nadu - 13Kms<br><br>J=Tindivanam Ancient Digambar Jain Temple Neru St, Tindivanam, Tamil Nadu 604001 - 32Kms<br><br>K=Mel Chittamur, Tamil Nadu - 18Kms<br><br> Bangalore, Karnataka - 270Kms<br><br></td>'+
    '<td><iframe width=640 height=480 frameborder=0 scrolling=no marginheight=0 marginwidth=0 src="https://maps.google.co.in/maps?saddr=Bangalore,+Karnataka&amp;daddr=Arihant+Giri+Digamabr+Jain+Temple,+Tiruvannamalai,+Tamil+Nadu+to:arni+to:Thiruppanamoor+Ancient+Digambar+Jain+Temple,+Thiruppanamoor,+Tamil+Nadu+to:Thiruparuthikundram+to:Arihant+Giri+Digamabr+Jain+Temple,+Tiruvannamalai,+Tamil+Nadu+to:Shri+Ponnur+Hills,+Kund+Kund+Nagar,+Tamilnadu+to:Birudur,+Tamil+Nadu+to:Nelliankulam,+Tamil+Nadu+to:Tindivanam+Ancient+Digambar+Jain+Temple,+Tindivanam+Ancient+Digambar+Jain+Temple,+Neru+St,+Tindivanam,+Tamil+Nadu+604001+to:Mel+Chittamur,+Villupuram,+Tamil+Nadu+to:Bangalore,+Karnataka&amp;hl=en&amp;sll=12.54384,78.571472&amp;sspn=1.747962,2.469177&amp;geocode=FU_uxQAdw_-fBCltTrTJcBauOzHgT35R6MPf-A%3BFXOtvwAdQIa4BCFcjn8uVRaL_SnzeQvpitesOzFcjn8uVRaL_Q%3BFYROwQAd6Me5BCkLKQT5WCmtOzGk8RSDIXSemw%3BFXfFwgAd4G2-BCE9ZZn9JEXhsSkVxijnw9pSOjE9ZZn9JEXhsQ%3BFUDBwwAdQ-S_BCEdKnsNARiiMSlVB2IyBsNSOjEdKnsNARiiMQ%3BFXOtvwAdQIa4BCFcjn8uVRaL_SnzeQvpitesOzFcjn8uVRaL_Q%3BFQHCvgAdIHG9BCE5SRiGkKzpMCn5sjdhLi9TOjE5SRiGkKzpMA%3BFXPDvgAdnhO_BCnH6V5cFyRTOjHPMaooZrDwUQ%3BFRmpvQAdME2_BCkXSNkTqSRTOjHzoPY2XkEtIg%3BFXutugAdzVa_BCkPgDAXU0dTOjHk-dEFW-Gy2w%3BFTlBuwAddEm9BCkN5nCKUjZTOjHyh4v1UAZekg%3BFU_uxQAdw_-fBCltTrTJcBauOzHgT35R6MPf-A&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;ll=12.597455,78.642883&amp;spn=1.747597,2.469177&amp;output=embed"></iframe></td></tr></table>';
  }else if(choice=='MH') {
    abc='<table width=90% border=0><tr><td align=left><h4>A=Nagpur, Maharashtra<br><br> B=Muktagiri Jain Temple Muktagiri Rd, Madhya Pradesh 420260<br><br> C=Bhatkuli, Maharashtra<br><br> D=Karanja, Maharashtra<br><br> E=Shirpur (Jain) SH 208, Shirpur, MH 444504<br><br> F=Jintur, Maharashtra<br><br> G=Kesapuri Camp, Majalgaon, Maharashtra<br><br> H=Kunthalgiri, Yasawandi, Maharashtra<br><br> I=Paithan, Maharashtra<br><br> J=Kachner, Maharashtra<br><br> K=Jatwada, Maharashtra<br><br> L=Ellora Caves Ellora cave Rd, Verul, Maharashtra 431102<br><br> M=Mangi Tungi<br><br> N=Mahuva, Gujarat<br><br> O=Saputara, Gujarat<br><br> P=Gajpanth Siddhakshetra Prabhat Nagar, Nashik, Maharashtra 422004<br><br> Q=Devlali Gaon, Devlali, Maharashtra</h4></td>'+
    '<td><iframe width=640 height=480 frameborder=0 scrolling=no marginheight=0 marginwidth=0 src="https://maps.google.co.in/maps?saddr=Nagpur,+Maharashtra&amp;daddr=Muktagiri+Jain+Temple,+Muktagiri+Road,+Malni,+Madhya+Pradesh+to:Bhatkuli,+Maharashtra+to:Karanja,+Maharashtra+to:Shirpur+(Jain),+SH+208,+Shirpur,+%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%B0%E0%A4%BE%E0%A4%B7%E0%A5%8D%E0%A4%9F%E0%A5%8D%E0%A4%B0+to:Jintur,+Maharashtra+to:Kesapuri+Camp,+Majalgaon,+Maharashtra+to:Kunthalgiri,+Yasawandi,+Maharashtra+to:Paithan,+Maharashtra+to:Kachner,+Maharashtra+to:Jatwada,+Maharashtra+to:Ellora,+Maharashtra+to:Mangi+Tungi,+Maharashtra+to:Mahua,+Gujarat+to:Saputara,+Gujarat+to:Gajpanth+Siddhakshetra,+Prabhat+Nagar,+Nashik,+Maharashtra+to:Deolali+Goan,+Nashik,+Maharashtra&amp;hl=en&amp;ie=UTF8&amp;sll=19.972458,76.10661&amp;sspn=5.831541,9.876709&amp;geocode=FcioQgEdG8q2BCkTrx-jpcDUOzErPrvQBn2zGQ%3BFRuORgEd4qufBCH8W3wmadjKViljeRoyBWDWOzH8W3wmadjKVg%3BFQMAPwEdoSKgBClT7C3q3rjWOzFrt9JaoV_-tg%3BFaZ_OAEdE2GeBCkNovccLzfROzEhQe9_MlE8xQ%3BFQ3aMwEdQEKWBCFW0ivYcrK0ISnfpPzQqenQOzFW0ivYcrK0IQ%3BFQ5NKwEdKjiSBCl356SgC2_QOzG-xBATlJtmjA%3BFSyaJAEd4pOKBCnXXOmGJbHaOzH1wW0xuuoFGw%3BFS8FGwEdMySDBCkli7qM-eHEOzFJjywN2WPRwA%3BFaRKKQEdBEJ-BClFFSu0dBPbOzHDdeoQgmpHig%3BFZCZLAEdp0V_BCnlBgtFkQnbOzGU1D2bqAY1ag%3BFT6BMAEd78p8BCmtYjW8-5bbOzE-xPQ8O7Q6uw%3BFVerMQEdfBZ7BCFSkraR1wj2_CkzojtUZ5LbOzFSkraR1wj2_A%3BFbbnPQEdJ5hqBClh2gwtlFveOzHcZ__ydpv-3w%3BFfjAQAEdxflbBClVYAn-y2HgOzH-cxik6rdwgw%3BFSYBOgEdyFhlBCnt3JQPYBHeOzFzLCAivr93MQ%3BFeIjMgEdQv5lBCE9xQ2EyTnwGCmviZVGdundOzE9xQ2EyTnwGA%3BFThMMAEdXJ1mBCnnNeEEXJXdOzHCyRacUfnElw&amp;oq=deola&amp;mra=ls&amp;t=m&amp;ll=20.045611,76.278076&amp;spn=5.828867,9.876709&amp;output=embed"></iframe></td></tr></table>';
  }else{
    abc='';
  }
  $(".bottomContainer").html(abc);
}
