#!/bin/sh

curDir=$PWD
convert=
[ "$1" = "-c" ] && convert="-c"

export dbDir=$(echo $PWD | perl -i -pe 's/(.*Dropbox).*/$1/g')

while read oDir; do
  oDir=$(echo "$oDir" | tr -d '\r')
  echo $curDir/$oDir
  cd $curDir/$oDir
  while read iDir; do
    iDir=$(echo "$iDir" | tr -d '\r')
	cd $curDir/$oDir/$iDir
    echo $PWD
    $dbDir/collaborate/createXML $convert
  done < "index.txt"
  cd $curDir
done < "index.txt"
