#!/bin/sh

curDir=$PWD
convert=
[ "$1" = "-c" ] && convert="-c"

cat <<EOF
<!doctype>
<html>
<head>
	<title>jsPDF</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="hi" />
	<script type="text/javascript" src="../libs/base64.js"></script>
	<script type="text/javascript" src="../libs/sprintf.js"></script>
	<script type="text/javascript" src="../jspdf.js"></script>
</head>

<body>

<h2>Simple Two-page Text Document</h2>
<a href="javascript:convertToPDF()">Convert To PDF</a>

<script type="text/javascript">

var doc = new jsPDF();

function convertToPDF() {
	createPages();
	// Output as Data URI
	doc.output('datauri');
}

function createPages() {

EOF

for dir in `find /mnt/hgfs/winshare/Personal/Dropbox/Public/HTML/myWebsite/jainDataBase/bhajans/. -maxdepth 1 -type d -name [^\.]\* | sed 's:^\./::' | head -1`
do
	cd $dir/main
    for file in *
    do
	  IFS=$'\n'
	  #dos2unix $file
      echo "  doc.text(20, 30, \"$file\");"
	  cntr=30;
	  for line in $(cat $file | dos2unix)
	  do
		l=$(echo "$line" | tr '\r' ' ' | sed 's/^\xEF\xBB\xBF//')
		cntr=$((cntr+20))
        echo "  doc.text(20, $cntr, \"$l\");"
	  done
	  echo "doc.addPage();"
	  #unix2dos $file
	done
done

cat <<EOF
  }
</script>
</body>
</html>
EOF
