document.write("<div id=आर्यिका-ज्ञानमती class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿संक्षिप्त और मध्यम रुचि वाले शिष्य की अपेक्षा प्ररूपणा - २ (अभेद विवक्षा) और २० (भेद विवक्षा)</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4>003</font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿गुणस्थान का लक्षण</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿१४ गुणस्थान</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4>010</font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿प्रमाद के अन्य ५ प्रकार</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿संख्या (भंग का जोड़) कैसे लाए</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿प्रस्तार - प्रथम प्रकार</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿प्रस्तार - द्वितीय प्रकार</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿प्रथम प्रस्तार का परिवर्तन</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿दूसरे प्रस्तार का परिवर्तन</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿नष्ट लाने की विधि</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿उद्दिष्ट लाने की विधि</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿प्रथम प्रस्तार का गूढ़ यन्त्र</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿दूसरे प्रस्तार का गूढ़ यंत्र</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿अप्रमत्त विरत (सातवां)</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿स्वस्थान अप्रमत्त विरत की विशषेता</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿सातिशय अप्रमत्त विरत का स्वरूप</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿तीन करण की विशषेता</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkBlue>﻿अपूर्वकरण गुणस्थान</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkGreen>﻿अपूर्वकरण का निरुक्तिपूर्वक लक्षण</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkBlue>﻿अपूर्वकरण - विशेष स्वरूप</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4>053</font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkBlue>﻿अपूर्वकरण परिणामों के कार्य</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4>055</font></a></li>");
document.write("        <li><a href='056-057.html'><font size=4><font color=darkPurple><b>056-057</b></font> - <font color=darkBlue>﻿अनिवृत्ति-करण गुणस्थान</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿सूक्ष्मसांपराय (दसवाँ)</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿कृष्टि किस क्रम से होती है ?</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿पूर्व और अपूर्व स्पर्धक में अंतर</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿उपशांत-कषाय (ग्यारहवाँ)</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿क्षीण-कषाय (बारहवां)</font></font></a></li>");
document.write("        <li><a href='063-064.html'><font size=4><font color=darkPurple><b>063-064</b></font> - <font color=darkBlue>﻿सयोग केवली जिन (तेरहवाँ गुणस्थान)</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkGreen>﻿अयोग केवली जिन (चौदहवाँ) गुणस्थान</font></font></a></li>");
document.write("        <li><a href='068-069.html'><font size=4><font color=darkPurple><b>068-069</b></font> - <font color=darkBlue>﻿सिद्धों के विशेषण एवं आठ मतों का खण्डन</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=सम्यग्ज्ञान-चंद्रिका class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkGreen>﻿मंगलाचरण</font></font></a></li>");
document.write("</ul></div>");
