document.write("<div id=ब्र-नेमिदत्त class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿पात्रकेसरी की कथा</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿भट्टाकलंकदेव की कथा</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿सनत्कुमार चक्रवर्त्ती की कथा</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿समन्‍त भद्राचार्य की कथा</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿संजयन्त मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿अंजन चोर की कथा</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿अनन्‍तमतीकी कथा</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿उद्दायन राजा की कथा</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿रेवती रानी की कथा</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿जिनेन्द्रभक्त की कथा</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkBlue>﻿वारिषेण मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkGreen>﻿विष्णुकुमार मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkBlue>﻿वज्रकुमार की कथा</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkGreen>﻿नागदत्त मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkBlue>﻿शिवभूति पुरोहित की कथा</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkGreen>﻿पवित्र हृदय वाले एक बालक की कथा</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkBlue>﻿धनदत्त राजा की कथा</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkGreen>﻿ब्रह्मदत्त की कथा</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿श्रेणिक राजा की कथा</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿पद्मरथ राजा की कथा</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿पंच नमस्कारमंत्र-माहात्म्य कथा</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿यम मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿दृढ़सूर्य की कथा</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿यमपाल चांडाल की कथा</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿मृगसेन धीवर की कथा</font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿वसुराजाकीकथा</font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿श्रीभूति - पुरोहित की कथा</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿नीली की कथा</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿कडारपिंग की कथा</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿देवरति राजा की कथा</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿गोपवती की कथा</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿वीरवती की कथा</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿सुरतराजा की कथा</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿विषयों में फँसे हुए संसारी जीव की कथा</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿चारूदत्त सेठ की कथा</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿पाराशर मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿सात्‍यकि और रूद्र की कथा</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿लौकिक ब्रह्मा की कथा</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿परिग्रह से डरे हुए दो भाइयों की कथा</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿धन से डरे हुए सागरदत्त की कथा</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿धन के लोभ से भ्रम में पड़े कुबेरदत्त की कथा</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿पिण्‍याकगन्‍ध की कथा</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿लुब्‍धक सेठ की कथा</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿वशिष्‍ठ तापसी की कथा</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿लक्ष्‍मीमती की कथा</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿पुष्‍पदत्ता की कथा</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿मरीचि की कथा</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿गन्‍धमित्र की कथा</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿गन्‍धर्वसेना की कथा</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿भीमराज की कथा</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿नागदत्ता की कथा</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿द्वीपायन मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿शराब पीने वालों की कथा</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿सगर चक्रवर्ती की कथा</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿मृगध्वज की कथा</font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿परशुराम की कथा</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿सुकुमाल मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿सुकौशल मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿गजकुमार मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿पणिक मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿भद्रबाहु मुनिराज की कथा</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿बत्तीस सेठ पुत्रों की कथा</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿धर्मघोष मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='064.html'><font size=4><font color=darkPurple><b>064</b></font> - <font color=darkGreen>﻿श्रीदत्त मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkBlue>﻿वृषभसेन की कथा</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿कार्तिकेय मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿अभयघोष मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿विद्युच्चर मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='069.html'><font size=4><font color=darkPurple><b>069</b></font> - <font color=darkBlue>﻿गुरूदत्त मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='070.html'><font size=4><font color=darkPurple><b>070</b></font> - <font color=darkGreen>﻿चिलात-पुत्र की कथा</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkBlue>﻿धन्य मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkGreen>﻿पाँच सौ मुनियों की कथा</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkBlue>﻿चाणक्य की कथा</font></font></a></li>");
document.write("        <li><a href='074.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkGreen>﻿वृषभसेन की कथा</font></font></a></li>");
document.write("        <li><a href='075.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkBlue>﻿शालिसिक्थ मच्छ के भावों की कथा</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkGreen>﻿सुभौम चक्रवर्ती की कथा</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkBlue>﻿शुभ राजा की कथा</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkGreen>﻿सुदृष्टि सुनार की कथा</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkBlue>﻿धर्मसिंह मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkGreen>﻿वृषभसेन की कथा</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkBlue>﻿जयसेन राजा की कथा</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkGreen>﻿शकटाल मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkBlue>﻿श्रद्धायुक्त मनुष्य की कथा</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkGreen>﻿आत्मनिन्दा करने वाली की कथा</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkBlue>﻿आत्मनिन्दा की कथा</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkGreen>﻿सोमशर्म मुनि की कथा</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkBlue>﻿कालाध्ययन की कथा</font></font></a></li>");
document.write("        <li><a href='088.html'><font size=4><font color=darkPurple><b>088</b></font> - <font color=darkGreen>﻿अकाल में शास्त्राभ्यास करनेवाले की कथा</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkBlue>﻿विनयी पुरूष की कथा</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkGreen>﻿अवग्रह-नियम लेनेवाले की कथा</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkBlue>﻿अभिमान करने वाली की कथा</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkGreen>﻿निह्नव-असल बात को छुपाने वाले की कथा</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkBlue>﻿अक्षरहीन अर्थ की कथा</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkGreen>﻿अर्थहीन वाक्य की कथा</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkBlue>﻿व्यंजनहीन अर्थ की कथा</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkGreen>﻿सुव्रत मुनिराज की कथा</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkBlue>﻿हरिषेण चक्रवर्ती की कथा</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkGreen>﻿हरिषेण चक्रवर्ती की कथा</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkBlue>﻿दूसरों के गुण ग्रहण करने की कथा</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkGreen>﻿जिनाभिषेक से प्रेम करने वाले की कथा</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkBlue>﻿भावानुराग-कथा</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkGreen>﻿प्रेमानुराग-कथा</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkBlue>﻿दूसरों के गुण ग्रहण करने की कथा</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkGreen>﻿धर्मानुराग-कथा</font></font></a></li>");
document.write("        <li><a href='105.html'><font size=4><font color=darkPurple><b>105</b></font> - <font color=darkBlue>﻿दूसरों के गुण ग्रहण करने की कथा</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><font color=darkPurple><b>106</b></font> - <font color=darkGreen>﻿सम्यक्त्व को न छोड़ने वाले की कथा</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkBlue>﻿सम्‍यग्‍दर्शन के प्रभाव की कथा</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkGreen>﻿रात्रिभोजन-त्‍याग-कथा</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>109</b></font> - <font color=darkBlue>﻿दान करने वालों की कथा</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>110</b></font> - <font color=darkGreen>﻿औषधिदान की कथा</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>111</b></font> - <font color=darkBlue>﻿शास्त्र-दान की कथा</font></font></a></li>");
document.write("        <li><a href='112.html'><font size=4><font color=darkPurple><b>112</b></font> - <font color=darkGreen>﻿अभयदान की कथा</font></font></a></li>");
document.write("        <li><a href='113.html'><font size=4><font color=darkPurple><b>113</b></font> - <font color=darkBlue>﻿करकण्डु राजा की कथा</font></font></a></li>");
document.write("        <li><a href='114.html'><font size=4><font color=darkPurple><b>114</b></font> - <font color=darkGreen>﻿जिनपूजन-प्रभाव-कथा</font></font></a></li>");
document.write("</ul></div>");
