
$( document ).ready(function() {
  $('.teekakaar').change(function() {
    window.location.href = $(this).val()
  })
})
function toggleTeeka(teeka) {
  $('#teeka'+teeka).toggle();
  if($('.teeka'+teeka).css('color')=='rgb(255, 0, 0)') {
    $('.teeka'+teeka).css('color', 'green')
  }else{
    $('.teeka'+teeka).css('color', 'red')
  }
}
function toggleSTeeka(teeka) {
  $('#steeka'+teeka).toggle();
  if($('#stitle'+teeka).css('color')=='rgb(255, 0, 0)') {
    $('#stitle'+teeka).css('color', 'green')
  }else{
    $('#stitle'+teeka).css('color', 'red')
  }
}
$( document ).ready(function() {
  mySel=$('select#select-native-0')
    $optgrp=$('<optgroup label="﻿१-जीवाधिकार">')
       $optgrp.append("<option value='01-01.html'><b>01-01</b> - ﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः ॥१॥</option>");
       $optgrp.append("<option value='01-02.html'><b>01-02</b> - ﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम् ॥२॥</option>");
       $optgrp.append("<option value='01-03.html'><b>01-03</b> - ﻿तन्निसर्गादधिगमाद्वा ॥३॥</option>");
       $optgrp.append("<option value='01-04.html'><b>01-04</b> - ﻿जीवाजीवास्रवबन्धसंवरनिर्जरामोक्षास्तत्त्वम् ॥४॥</option>");
       $optgrp.append("<option value='01-05.html'><b>01-05</b> - ﻿नामस्थापनाद्रव्यभाव तस्तन्न्यासः ॥५॥</option>");
       $optgrp.append("<option value='01-06.html'><b>01-06</b> - ﻿प्रमाणनयैरधिगमः ॥६॥</option>");
       $optgrp.append("<option value='01-07.html'><b>01-07</b> - ﻿निर्देशस्वामित्वसाधनाधिकरणस्थितिविधानतः ॥७॥</option>");
       $optgrp.append("<option value='01-08.html'><b>01-08</b> - ﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च ॥८॥</option>");
       $optgrp.append("<option value='01-09.html'><b>01-09</b> - ﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम् ॥९॥</option>");
       $optgrp.append("<option value='01-10.html'><b>01-10</b> - ﻿तत्प्रमाणे ॥१०॥</option>");
       $optgrp.append("<option value='01-11.html'><b>01-11</b> - ﻿आद्ये परोक्षम् ॥११॥</option>");
       $optgrp.append("<option value='01-12.html'><b>01-12</b> - ﻿प्रत्यक्षमन्यत् ॥१२॥</option>");
       $optgrp.append("<option value='01-13.html'><b>01-13</b> - ﻿मतिः स्मृतिः संज्ञा चिन्ताऽभिनिबोध इत्यनर्थान्तरम् ॥१३॥</option>");
       $optgrp.append("<option value='01-14.html'><b>01-14</b> - ﻿तदिन्द्रयानिन्द्रिय निमित्तम् ॥१४॥</option>");
       $optgrp.append("<option value='01-15.html'><b>01-15</b> - ﻿अवग्रहेहावाय धारणाः ॥१५॥</option>");
       $optgrp.append("<option value='01-16.html'><b>01-16</b> - ﻿बहुबहुविधक्षिप्रानिःसृतानुक्तध्रुवाणां सेतराणाम्‌ ॥१६॥</option>");
       $optgrp.append("<option value='01-17.html'><b>01-17</b> - ﻿अर्थस्य ॥१७॥</option>");
       $optgrp.append("<option value='01-18.html'><b>01-18</b> - ﻿व्यञ्जनस्यावग्रहः ॥१८॥</option>");
       $optgrp.append("<option value='01-19.html'><b>01-19</b> - ﻿न चक्षुरनिन्द्रियाभ्याम् ॥१९॥</option>");
       $optgrp.append("<option value='01-20.html'><b>01-20</b> - ﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌ ॥२०॥</option>");
       $optgrp.append("<option value='01-21.html'><b>01-21</b> - ﻿भवप्रत्ययोऽवधिर्देवनारकाणाम् ॥२१॥</option>");
       $optgrp.append("<option value='01-22.html'><b>01-22</b> - ﻿क्षयोपशमनिमित्तः षड्विकल्पः शेषाणाम् ॥२२॥</option>");
       $optgrp.append("<option value='01-23.html'><b>01-23</b> - ﻿ऋजुविपुलमती मनःपर्ययः ॥२३॥</option>");
       $optgrp.append("<option value='01-24.html'><b>01-24</b> - ﻿विशुद्धयप्रतिपाताभ्यां तद्विशेषः ॥२४॥</option>");
       $optgrp.append("<option value='01-25.html'><b>01-25</b> - ﻿विशुद्धिक्षेत्रस्वामिविषयेभ्योऽवधिमनःपर्यययोः ॥२५॥</option>");
       $optgrp.append("<option value='01-26.html'><b>01-26</b> - ﻿मतिश्रुतयोर्निबन्धो द्रव्येष्वसर्वपर्यायेषु ॥२६॥</option>");
       $optgrp.append("<option value='01-27.html'><b>01-27</b> - ﻿रूपिष्ववधेः ॥२७॥</option>");
       $optgrp.append("<option value='01-28.html'><b>01-28</b> - ﻿तदनन्तभागे मनःपर्ययस्य ॥२८॥</option>");
       $optgrp.append("<option value='01-29.html'><b>01-29</b> - ﻿सर्वद्रव्यपर्यायेषु केवलस्य ॥२९॥</option>");
       $optgrp.append("<option value='01-30.html'><b>01-30</b> - ﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः ॥३०॥</option>");
       $optgrp.append("<option value='01-31.html'><b>01-31</b> - ﻿मतिश्रुतावधयो विपर्ययश्‍च ॥३१॥</option>");
       $optgrp.append("<option value='01-32.html'><b>01-32</b> - ﻿सदसतोरविशेषाद्यदृच्छोपलब्धेरुन्मत्तवत् ॥३२॥</option>");
       $optgrp.append("<option value='01-33.html'><b>01-33</b> - ﻿नैगमसंग्रहव्यवहारर्जुसूत्रशब्दसमभिरूढैवंभूता नयाः ॥३३॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿२-जीवाधिकार">')
       $optgrp.append("<option value='02-01.html'><b>02-01</b> - ﻿औपशमिकक्षायिकौ भावौ मिश्रश्च जीवस्य स्वतत्त्वमौदयिकपारिणामिकौ च ॥१॥</option>");
       $optgrp.append("<option value='02-02.html'><b>02-02</b> - ﻿द्विनवाष्टादशैकविंशतित्रिभेदा यथाक्रमम् ॥२॥</option>");
       $optgrp.append("<option value='02-03.html'><b>02-03</b> - ﻿सम्यक्त्वचारित्रे ॥३॥</option>");
       $optgrp.append("<option value='02-04.html'><b>02-04</b> - ﻿ज्ञानदर्शनदानलाभभोगोपभोगवीर्याणि च ॥४॥</option>");
       $optgrp.append("<option value='02-05.html'><b>02-05</b> - ﻿ज्ञानाज्ञानदर्शन लब्धयश्‍चतुस्त्रित्रि पञ्चभेदाः सम्यक्त्वचारित्र संयमासंयमाश्‍च ॥५॥</option>");
       $optgrp.append("<option value='02-06.html'><b>02-06</b> - ﻿गतिकषायलिंग-मिथ्यादर्शनाज्ञानासंयतासिद्धलेश्याश्‍चतुश्‍चतुस्त्र्यैकैकैकैक-षड्भेदाः ॥६॥</option>");
       $optgrp.append("<option value='02-07.html'><b>02-07</b> - ﻿जीवभव्याभव्यत्वानि च ॥७॥</option>");
       $optgrp.append("<option value='02-08.html'><b>02-08</b> - ﻿उपयोगो लक्षणम् ॥८॥</option>");
       $optgrp.append("<option value='02-09.html'><b>02-09</b> - ﻿स द्विविधोऽष्ट-चतुर्भेदः ॥९॥</option>");
       $optgrp.append("<option value='02-10.html'><b>02-10</b> - ﻿संसारिणो मुक्ताश्‍च ॥१०॥</option>");
       $optgrp.append("<option value='02-11.html'><b>02-11</b> - ﻿समनस्काऽमनस्काः ॥११॥</option>");
       $optgrp.append("<option value='02-12.html'><b>02-12</b> - ﻿संसारिणस्त्रसस्थावराः ॥१२॥</option>");
       $optgrp.append("<option value='02-13.html'><b>02-13</b> - ﻿पृथिव्यप्तेजो वायु-वनस्पतयः स्थावराः ॥१३॥</option>");
       $optgrp.append("<option value='02-14.html'><b>02-14</b> - ﻿द्वीन्द्रियादयस्त्रसाः ॥१४॥</option>");
       $optgrp.append("<option value='02-15.html'><b>02-15</b> - ﻿पंचेद्रियाणि ॥१५॥</option>");
       $optgrp.append("<option value='02-16.html'><b>02-16</b> - ﻿द्विविधानि ॥१६॥</option>");
       $optgrp.append("<option value='02-17.html'><b>02-17</b> - ﻿निर्वृत्त्युपकरणे द्रव्येन्द्रियम्‌ ॥१७॥</option>");
       $optgrp.append("<option value='02-18.html'><b>02-18</b> - ﻿लब्ध्युपयोगो भावेन्द्रियम् ॥१८॥</option>");
       $optgrp.append("<option value='02-19.html'><b>02-19</b> - ﻿स्पर्शन-रसन-घ्राण-चक्षुःश्रोत्राणि ॥१९॥</option>");
       $optgrp.append("<option value='02-20.html'><b>02-20</b> - ﻿स्पर्श-रस-गन्ध-वर्ण-शब्दास्तदर्थाः ॥२०॥</option>");
       $optgrp.append("<option value='02-21.html'><b>02-21</b> - ﻿श्रुतमनिन्द्रियस्य ॥२१॥</option>");
       $optgrp.append("<option value='02-22.html'><b>02-22</b> - ﻿वनस्पत्यन्तानामेकम् ॥२२॥</option>");
       $optgrp.append("<option value='02-23.html'><b>02-23</b> - ﻿कृमि-पिपीलिका-भ्रमर-मनुष्यादीनामेकैकवृद्धानि ॥२३॥</option>");
       $optgrp.append("<option value='02-24.html'><b>02-24</b> - ﻿संज्ञिनः समनस्काः ॥२४॥</option>");
       $optgrp.append("<option value='02-25.html'><b>02-25</b> - ﻿विग्रहगतौ कर्मयोगः ॥२५॥</option>");
       $optgrp.append("<option value='02-26.html'><b>02-26</b> - ﻿अनुश्रेणिः गतिः ॥२६॥</option>");
       $optgrp.append("<option value='02-27.html'><b>02-27</b> - ﻿अविग्रहा जीवस्य ॥२७॥</option>");
       $optgrp.append("<option value='02-28.html'><b>02-28</b> - ﻿विग्रहवती च संसारिणः प्राक् चतुर्भ्यः ॥२८॥</option>");
       $optgrp.append("<option value='02-29.html'><b>02-29</b> - ﻿एकसमयाऽविग्रहा ॥२९॥</option>");
       $optgrp.append("<option value='02-30.html'><b>02-30</b> - ﻿एकं द्वौ त्रीन्वानाहारकः ॥३०॥</option>");
       $optgrp.append("<option value='02-31.html'><b>02-31</b> - ﻿सम्मूर्च्छन-गर्भोपपादा जन्म ॥३१॥</option>");
       $optgrp.append("<option value='02-32.html'><b>02-32</b> - ﻿सचित्तशीतसंवृताः सेतरा मिश्राश्‍चैकशस्तद्योनयः ॥३२॥</option>");
       $optgrp.append("<option value='02-33.html'><b>02-33</b> - ﻿जरायुजाण्डजपोतानां गर्भः ॥३३॥</option>");
       $optgrp.append("<option value='02-34.html'><b>02-34</b> - ﻿देवनारकाणामुपपादः ॥३४॥</option>");
       $optgrp.append("<option value='02-35.html'><b>02-35</b> - ﻿शेषाणां सम्मूर्च्छनं ॥३५॥</option>");
       $optgrp.append("<option value='02-36.html'><b>02-36</b> - ﻿औदारिक-वैक्रियिकाहारक-तैजस-कार्मणानि शरीराणि ॥३६॥</option>");
       $optgrp.append("<option value='02-37.html'><b>02-37</b> - ﻿परं परं सूक्ष्मम् ॥३७॥</option>");
       $optgrp.append("<option value='02-38.html'><b>02-38</b> - ﻿प्रदेशतोऽसंख्येयगुणं प्राक् तैजसात् ॥३८॥</option>");
       $optgrp.append("<option value='02-39.html'><b>02-39</b> - ﻿अनन्तगुणे परे ॥३९॥</option>");
       $optgrp.append("<option value='02-40.html'><b>02-40</b> - ﻿अप्रतीघाते ॥४०॥</option>");
       $optgrp.append("<option value='02-41.html'><b>02-41</b> - ﻿अनादिसंबन्धे च ॥४१॥</option>");
       $optgrp.append("<option value='02-42.html'><b>02-42</b> - ﻿सर्वस्य ॥४२॥</option>");
       $optgrp.append("<option value='02-43.html'><b>02-43</b> - ﻿तदादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः ॥४३॥</option>");
       $optgrp.append("<option value='02-44.html'><b>02-44</b> - ﻿निरुपभोगमन्त्यम् ॥४४॥</option>");
       $optgrp.append("<option value='02-45.html'><b>02-45</b> - ﻿गर्भसम्मूर्च्छनजमाद्यम्‌ ॥४५॥</option>");
       $optgrp.append("<option value='02-46.html'><b>02-46</b> - ﻿औपपादिकं वैक्रियिकम्‌ ॥४६॥</option>");
       $optgrp.append("<option value='02-47.html'><b>02-47</b> - ﻿लब्धिप्रत्ययं च॥४७॥</option>");
       $optgrp.append("<option value='02-48.html'><b>02-48</b> - ﻿तैजसमपि ॥४८॥</option>");
       $optgrp.append("<option value='02-49.html'><b>02-49</b> - ﻿शुभं विशुद्धमव्याघाति चाहारकं प्रमत्तसंयतस्यैव ॥४९॥</option>");
       $optgrp.append("<option value='02-50.html'><b>02-50</b> - ﻿नारकसंमूर्च्छिनो नपुंसकानि ॥५०॥</option>");
       $optgrp.append("<option value='02-51.html'><b>02-51</b> - ﻿न देवाः ॥५१॥</option>");
       $optgrp.append("<option value='02-52.html'><b>02-52</b> - ﻿शेषास्त्रिवेदाः ॥५२॥</option>");
       $optgrp.append("<option value='02-53.html'><b>02-53</b> - ﻿औपपादिक चरमोत्तम-देहाऽसंख्येय-वर्षायुषोऽनपवर्त्यायुषः ॥५३॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿३-जीवाधिकार">')
       $optgrp.append("<option value='03-01.html'><b>03-01</b> - ﻿रत्न-शर्करा-बालुका-पंक-धूम-तमो-महातमः प्रभा भूमयो घनाम्बुवाताकाश प्रतिष्ठाः सप्ताऽधोऽधः॥१॥</option>");
       $optgrp.append("<option value='03-02.html'><b>03-02</b> - ﻿तासु त्रिंशत्पंचविंशति पंचदशदश-त्रि-पंचोनैक-नरक-शतसहस्राणि पंच चैव यथाक्रमम्॥२॥</option>");
       $optgrp.append("<option value='03-03.html'><b>03-03</b> - ﻿नारका नित्याऽशुभतर-लेश्या-परिणामदेह-वेदना-विक्रियाः॥३॥</option>");
       $optgrp.append("<option value='03-04.html'><b>03-04</b> - ﻿परस्परोदीरित-दुःखाः॥४॥</option>");
       $optgrp.append("<option value='03-05.html'><b>03-05</b> - ﻿संक्लिष्टासुरोदीरित-दुःखाश्‍च प्राक् चतुर्थ्याः॥५॥</option>");
       $optgrp.append("<option value='03-06.html'><b>03-06</b> - ﻿तेष्वेक-त्रि-सप्त-दश-सप्तदश-द्वाविंशति-त्रयस्त्रिंशत्सागरोपमा सत्त्वानां परा स्थितिः॥६॥</option>");
       $optgrp.append("<option value='03-07.html'><b>03-07</b> - ﻿जम्बूद्वीप-लवणोदादयः शुभनामानो द्वीप-समुद्रा॥७॥</option>");
       $optgrp.append("<option value='03-08.html'><b>03-08</b> - ﻿द्विर्द्विर्विष्कम्भाः पूर्वपूर्वपरिक्षेपिणो वलयाकृतयः॥८॥</option>");
       $optgrp.append("<option value='03-09.html'><b>03-09</b> - ﻿तन्मध्ये मेरुनाभिर्वृत्तो योजनशतसहस्रविष्कम्भो जम्बूद्वीपः॥९॥</option>");
       $optgrp.append("<option value='03-10.html'><b>03-10</b> - ﻿भरतहैमवत-हरि-विदेह-रम्यकहैरण्यवतैरावतवर्षाः क्षेत्राणि॥१०॥</option>");
       $optgrp.append("<option value='03-11.html'><b>03-11</b> - ﻿तद्विभाजिनः पूर्वापरायता हिमवन्महाहिमवन्निषध-नील-रुक्मि-शिखरिणो वर्षधर-पर्वताः॥११॥</option>");
       $optgrp.append("<option value='03-12.html'><b>03-12</b> - ﻿हेमार्जुन-तपनीय वैडूर्य-रजत हेममयाः॥१२॥</option>");
       $optgrp.append("<option value='03-13.html'><b>03-13</b> - ﻿मणि-विचित्र-पार्श्‍वा उपरि मूले च तुल्यविस्ताराः॥१३॥</option>");
       $optgrp.append("<option value='03-14.html'><b>03-14</b> - ﻿पद्ममहापद्मतिगिञ्छकेशरि महापुण्डरीकपुण्डरीका-हृदास्तेषामुपरि॥१४॥</option>");
       $optgrp.append("<option value='03-15.html'><b>03-15</b> - ﻿प्रथमो योजन-सहस्रायामस्तदर्द्धविष्कम्भो हृदः।॥१५॥</option>");
       $optgrp.append("<option value='03-16.html'><b>03-16</b> - ﻿दशयोजनावगाहः॥१६॥</option>");
       $optgrp.append("<option value='03-17.html'><b>03-17</b> - ﻿तन्मध्ये योजनं पुष्करम्॥१७॥</option>");
       $optgrp.append("<option value='03-18.html'><b>03-18</b> - ﻿तद् द्विगुण-द्विगुणा हृदाः पुष्कराणि च॥१८॥</option>");
       $optgrp.append("<option value='03-19.html'><b>03-19</b> - ﻿तन्निवासिन्यो देव्यः श्री-ह्री-धृति-कीर्ति-बुद्धि-लक्ष्म्यः पल्योपमस्थितयः ससामानिक परिषत्काः ॥१९॥</option>");
       $optgrp.append("<option value='03-20.html'><b>03-20</b> - ﻿गंगासिन्धु रोहिद्रोहितास्या-हरिद्धरिकान्ता सीतासीतोदा-नारीनरकान्ता सुवर्णरूप्यकूला रक्तारक्तोदाः सरितस्तन्मध्यगाः ॥२०॥</option>");
       $optgrp.append("<option value='03-21.html'><b>03-21</b> - ﻿द्वयोर्द्वयोः पूर्वाः पूर्वगाः॥२१॥</option>");
       $optgrp.append("<option value='03-22.html'><b>03-22</b> - ﻿शेषास्त्वपरगाः॥२२॥</option>");
       $optgrp.append("<option value='03-23.html'><b>03-23</b> - ﻿चतुर्दशनदीसहस्रपरिवृता गंगासिन्ध्वादयो नद्यः॥२३॥</option>");
       $optgrp.append("<option value='03-24.html'><b>03-24</b> - ﻿भरतः षड्विंशति-पंचयोजनशत-विस्तारः षट्चैकोनविंशतिभागा-योजनस्य ॥२४॥</option>");
       $optgrp.append("<option value='03-25.html'><b>03-25</b> - ﻿तद् द्विगुण द्विगुणविस्तारा वर्षधरवर्षा विदेहान्ताः॥२५॥</option>");
       $optgrp.append("<option value='03-26.html'><b>03-26</b> - ﻿उत्तरा दक्षिण-तुल्याः ॥२६॥</option>");
       $optgrp.append("<option value='03-27.html'><b>03-27</b> - ﻿भरतैरावतयोर्वृद्धिह्रासौ षट्‍समयाभ्यामुत्सर्पिण्यवसर्पिणीभ्याम्‌ ॥२७॥</option>");
       $optgrp.append("<option value='03-28.html'><b>03-28</b> - ﻿ताभ्यामपरा भूमयोऽवस्थिताः॥२८॥</option>");
       $optgrp.append("<option value='03-29.html'><b>03-29</b> - ﻿एकद्वित्रिपल्योपम-स्थितयो हैमवतक हारिवर्षक दैवकुरुवकाः॥२९॥</option>");
       $optgrp.append("<option value='03-30.html'><b>03-30</b> - ﻿तथोत्तराः॥३०॥</option>");
       $optgrp.append("<option value='03-31.html'><b>03-31</b> - ﻿विदेहेषु संख्येयकालाः॥३१॥</option>");
       $optgrp.append("<option value='03-32.html'><b>03-32</b> - ﻿भरतस्य विष्कम्भो जम्बूद्वीपस्य नवतिशतभागः॥३२॥</option>");
       $optgrp.append("<option value='03-33.html'><b>03-33</b> - ﻿द्विर्धातकीखण्डे॥३३॥</option>");
       $optgrp.append("<option value='03-34.html'><b>03-34</b> - ﻿पुष्करार्द्धे च॥३४॥</option>");
       $optgrp.append("<option value='03-35.html'><b>03-35</b> - ﻿प्राङ् मानुषोत्तरान्मनुष्याः॥३५॥</option>");
       $optgrp.append("<option value='03-36.html'><b>03-36</b> - ﻿आर्या म्लेच्छाश्‍च॥३६॥</option>");
       $optgrp.append("<option value='03-37.html'><b>03-37</b> - ﻿भरतैरावतविदेहाः कर्मभूमयोऽन्यत्र देवकुरूत्तरकुरुभ्यः॥३७॥</option>");
       $optgrp.append("<option value='03-38.html'><b>03-38</b> - ﻿नृस्थितीपरावरे त्रिपल्योपमान्तर्मुहूर्ते॥३८॥</option>");
       $optgrp.append("<option value='03-39.html'><b>03-39</b> - ﻿तिर्यग्योनिजानां च॥३९॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿४-जीवाधिकार">')
       $optgrp.append("<option value='04-01.html'><b>04-01</b> - ﻿देवाश्चतुर्णिकाया: ॥१॥</option>");
       $optgrp.append("<option value='04-02.html'><b>04-02</b> - ﻿आदितस्त्रिषु पीतान्तलेश्या: ॥२॥</option>");
       $optgrp.append("<option value='04-03.html'><b>04-03</b> - ﻿दशाष्ट-पञ्च-द्वादश-विकल्पा कल्पोपपन्न पर्यन्ता: ॥३॥</option>");
       $optgrp.append("<option value='04-04.html'><b>04-04</b> - ﻿इंद्र-सामानिक-त्रायस्त्रिंश-पारिषदात्मरक्ष-लोकपालानीक-प्रकीर्णकाभियोग्यकिल्विषिकाश्चैकश: ॥४॥</option>");
       $optgrp.append("<option value='04-05.html'><b>04-05</b> - ﻿त्रायस्त्रिंश-लोकपाल-वर्ज्या व्यंतरज्योतिष्का: ॥५॥</option>");
       $optgrp.append("<option value='04-06.html'><b>04-06</b> - ﻿पूर्वयोर्द्वीन्द्राः ॥६॥</option>");
       $optgrp.append("<option value='04-07.html'><b>04-07</b> - ﻿काय-प्रवीचारा आ ऐशानात् ॥७॥</option>");
       $optgrp.append("<option value='04-08.html'><b>04-08</b> - ﻿शेषा: स्पर्श-रूप-शब्द-मन: प्रवीचारा: ॥८॥</option>");
       $optgrp.append("<option value='04-09.html'><b>04-09</b> - ﻿परेऽप्रवीचारा: ॥९॥</option>");
       $optgrp.append("<option value='04-10.html'><b>04-10</b> - ﻿भवन-वासिनोऽसुरनाग-विद्युत्सुपर्णाग्निवातस्तनितोदधि-द्वीप-दिक्कुमारा: ॥१०॥</option>");
       $optgrp.append("<option value='04-11.html'><b>04-11</b> - ﻿व्यन्तरा: किन्नर-किम्पुरुष-महोरग-गन्धर्व-यक्ष-राक्षस-भूत-पिशाचा: ॥११॥</option>");
       $optgrp.append("<option value='04-12.html'><b>04-12</b> - ﻿ज्योतिष्का: सूर्याचन्द्रमसौ ग्रह-नक्षत्र-प्रकीर्णक-तारकाश्च ॥१२॥</option>");
       $optgrp.append("<option value='04-13.html'><b>04-13</b> - ﻿मेरु-प्रदक्षिणा नित्यगतयो नृलोके ॥१३॥</option>");
       $optgrp.append("<option value='04-14.html'><b>04-14</b> - ﻿तत्कृत: काल विभाग: ॥१४॥</option>");
       $optgrp.append("<option value='04-15.html'><b>04-15</b> - ﻿बहिरवस्थिता: ॥१५॥</option>");
       $optgrp.append("<option value='04-16.html'><b>04-16</b> - ﻿वैमानिका: ॥१६॥</option>");
       $optgrp.append("<option value='04-17.html'><b>04-17</b> - ﻿कल्पोपपन्ना: कल्पातीताश्च ॥१७॥</option>");
       $optgrp.append("<option value='04-18.html'><b>04-18</b> - ﻿उपर्युपरि ॥१८॥</option>");
       $optgrp.append("<option value='04-19.html'><b>04-19</b> - ﻿सौधर्मेशान-सानत्कुमार-माहेन्द्र-ब्रह्म-ब्रह्मोत्तर-लान्तव-कापिष्ट-शुक्र-महाशुक्र-शतार-सहस्रारेष्वानतप्राणत-योरारणाच्युतयोर्नवसु ग्रैवेयकेषु विजय-वैजयन्त जयन्तापराजितेषु सर्वार्थ-सिद्धौ च ॥१९॥</option>");
       $optgrp.append("<option value='04-20.html'><b>04-20</b> - ﻿स्थिति-प्रभाव-सुख-द्युति-लेश्याविशुद्धीन्द्रियावधि-विषय-तोऽधिका: ॥२०॥</option>");
       $optgrp.append("<option value='04-21.html'><b>04-21</b> - ﻿गति-शरीर-परिग्रहाभिमानतो हीना: ॥२१॥</option>");
       $optgrp.append("<option value='04-22.html'><b>04-22</b> - ﻿पीत-पद्म-शुक्ल-लेश्या द्वि-त्रि-शेषेषु ॥२२॥</option>");
       $optgrp.append("<option value='04-23.html'><b>04-23</b> - ﻿प्राग्ग्रैवेयकेभ्य: कल्पा: ॥२३॥</option>");
       $optgrp.append("<option value='04-24.html'><b>04-24</b> - ﻿ब्रह्म-लोकालया लौकान्तिका: ॥२४॥</option>");
       $optgrp.append("<option value='04-25.html'><b>04-25</b> - ﻿सारस्वतादित्य वह्न्यरुण-गर्दतोय-तुषिताव्या-बाधारिष्टाश्च ॥२५॥</option>");
       $optgrp.append("<option value='04-26.html'><b>04-26</b> - ﻿विजयादिषु द्वि-चरमा: ॥२६॥</option>");
       $optgrp.append("<option value='04-27.html'><b>04-27</b> - ﻿औपपादिक-मनुष्येभ्य: शेषास्तिर्यग्योनय: ॥२७॥</option>");
       $optgrp.append("<option value='04-28.html'><b>04-28</b> - ﻿स्थितिरसुर-नाग-सुपर्ण-द्वीपशेषाणां-सागरोपम-त्रिपल्योपमार्द्धहीन-मिता: ॥२८॥</option>");
       $optgrp.append("<option value='04-29.html'><b>04-29</b> - ﻿सौधर्मेशानयो: सागरोपमेऽधिके ॥२९॥</option>");
       $optgrp.append("<option value='04-30.html'><b>04-30</b> - ﻿सानत्कुमार-माहेन्द्रयो: सप्त ॥३०॥</option>");
       $optgrp.append("<option value='04-31.html'><b>04-31</b> - ﻿त्रिसप्त-नवैकादश-त्रयोदश-पञ्चदशभिरधिकानि तु ॥३१॥</option>");
       $optgrp.append("<option value='04-32.html'><b>04-32</b> - ﻿आरणाच्युता-दूर्ध्वमेकैकेन नवसु ग्रैवेयकेषु विजयादिषु सर्वार्थसिद्धौ च ॥३२॥</option>");
       $optgrp.append("<option value='04-33.html'><b>04-33</b> - ﻿अपरा पल्योपममधिकम् ॥३३॥</option>");
       $optgrp.append("<option value='04-34.html'><b>04-34</b> - ﻿परत: परत: पूर्वा पूर्वाऽनन्तरा ॥३४॥</option>");
       $optgrp.append("<option value='04-35.html'><b>04-35</b> - ﻿नारकाणां च द्वितीयादिषु ॥३५॥</option>");
       $optgrp.append("<option value='04-36.html'><b>04-36</b> - ﻿दश-वर्षसहस्राणि प्रथमायाम् ॥३६॥</option>");
       $optgrp.append("<option value='04-37.html'><b>04-37</b> - ﻿भवनेषु च ॥३७॥</option>");
       $optgrp.append("<option value='04-38.html'><b>04-38</b> - ﻿व्यन्तराणां च ॥३८॥</option>");
       $optgrp.append("<option value='04-39.html'><b>04-39</b> - ﻿परा पल्योपममधिकम् ॥३९॥</option>");
       $optgrp.append("<option value='04-40.html'><b>04-40</b> - ﻿ज्योतिष्काणां च ॥४०॥</option>");
       $optgrp.append("<option value='04-41.html'><b>04-41</b> - ﻿तदष्टभागोऽपरा ॥४१॥</option>");
       $optgrp.append("<option value='04-42.html'><b>04-42</b> - ﻿लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम् ॥४२॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿५-अजीवाधिकार">')
       $optgrp.append("<option value='05-01.html'><b>05-01</b> - ﻿अजीव-काया-धर्माधर्माकाश-पुद्गला: ॥१॥</option>");
       $optgrp.append("<option value='05-02.html'><b>05-02</b> - ﻿द्रव्याणि ॥२॥</option>");
       $optgrp.append("<option value='05-03.html'><b>05-03</b> - ﻿जीवाश्च ॥३॥</option>");
       $optgrp.append("<option value='05-04.html'><b>05-04</b> - ﻿नित्यावस्थितान्यरूपाणि ॥४॥</option>");
       $optgrp.append("<option value='05-05.html'><b>05-05</b> - ﻿रूपिण: पुद्गला: ॥५॥</option>");
       $optgrp.append("<option value='05-06.html'><b>05-06</b> - ﻿आ आकाशादेक-द्रव्याणि ॥६॥</option>");
       $optgrp.append("<option value='05-07.html'><b>05-07</b> - ﻿निष्क्रियाणि च ॥७॥</option>");
       $optgrp.append("<option value='05-08.html'><b>05-08</b> - ﻿असंख्येया: प्रदेशा धर्माधर्मैकजीवानाम् ॥८॥</option>");
       $optgrp.append("<option value='05-09.html'><b>05-09</b> - ﻿आकाशस्यानन्ता: ॥९॥</option>");
       $optgrp.append("<option value='05-10.html'><b>05-10</b> - ﻿संख्येयासंख्येयाश्च पुद्गलानाम् ॥१०॥</option>");
       $optgrp.append("<option value='05-11.html'><b>05-11</b> - ﻿नाणो: ॥११॥</option>");
       $optgrp.append("<option value='05-12.html'><b>05-12</b> - ﻿लोकाकाशेऽवगाह: ॥१२॥</option>");
       $optgrp.append("<option value='05-13.html'><b>05-13</b> - ﻿धर्माधर्मयो: कृत्स्ने ॥१३॥</option>");
       $optgrp.append("<option value='05-14.html'><b>05-14</b> - ﻿एकप्रदेशादिषु भाज्य: पुद्गलानाम् ॥१४॥</option>");
       $optgrp.append("<option value='05-15.html'><b>05-15</b> - ﻿असंख्येय-भागादिषु जीवानाम् ॥१५॥</option>");
       $optgrp.append("<option value='05-16.html'><b>05-16</b> - ﻿प्रदेश-संहार-विसर्पाभ्यां प्रदीपवत् ॥१६॥</option>");
       $optgrp.append("<option value='05-17.html'><b>05-17</b> - ﻿गति-स्थित्युपग्रहौ धर्माधर्मयोरुपकार: ॥१७॥</option>");
       $optgrp.append("<option value='05-18.html'><b>05-18</b> - ﻿आकाशस्या-वगाह: ॥१८॥</option>");
       $optgrp.append("<option value='05-19.html'><b>05-19</b> - ﻿शरीरवाङ्मन:-प्राणापाना पुद्गलानाम् ॥१९॥</option>");
       $optgrp.append("<option value='05-20.html'><b>05-20</b> - ﻿सुख-दु:ख-जीवितमरणोपग्रहाश्च ॥२०॥</option>");
       $optgrp.append("<option value='05-21.html'><b>05-21</b> - ﻿परस्परोपग्रहो जीवानाम् ॥२१॥</option>");
       $optgrp.append("<option value='05-22.html'><b>05-22</b> - ﻿वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य ॥२२॥</option>");
       $optgrp.append("<option value='05-23.html'><b>05-23</b> - ﻿स्पर्श-रस-गंध-वर्णवन्त: पुद्गला: ॥२३॥</option>");
       $optgrp.append("<option value='05-24.html'><b>05-24</b> - ﻿शब्द-बंध-सौक्ष्म्य-स्थौल्य-संस्थान-भेद-तमश्छायातपोद्योतवन्तश्च ॥२४॥</option>");
       $optgrp.append("<option value='05-25.html'><b>05-25</b> - ﻿अणव: स्कन्धाश्च ॥२५॥</option>");
       $optgrp.append("<option value='05-26.html'><b>05-26</b> - ﻿भेद-संघातेभ्य उत्पद्यन्ते ॥२६॥</option>");
       $optgrp.append("<option value='05-27.html'><b>05-27</b> - ﻿भेदादणु: ॥२७॥</option>");
       $optgrp.append("<option value='05-28.html'><b>05-28</b> - ﻿भेद-संघाताभ्यां चाक्षुष: ॥२८॥</option>");
       $optgrp.append("<option value='05-29.html'><b>05-29</b> - ﻿सद् द्रव्य-लक्षणम् ॥२९॥</option>");
       $optgrp.append("<option value='05-30.html'><b>05-30</b> - ﻿उत्पाद-व्यय-ध्रौव्य-युक्तं सत् ॥३०॥</option>");
       $optgrp.append("<option value='05-31.html'><b>05-31</b> - ﻿तद्भावाव्ययं नित्यम् ॥३१॥</option>");
       $optgrp.append("<option value='05-32.html'><b>05-32</b> - ﻿अर्पितानर्पितसिद्धे: ॥३२॥</option>");
       $optgrp.append("<option value='05-33.html'><b>05-33</b> - ﻿स्निग्ध-रूक्षत्वाद् बन्धः ॥३३॥</option>");
       $optgrp.append("<option value='05-34.html'><b>05-34</b> - ﻿न जघन्य-गुणानाम् ॥३४॥</option>");
       $optgrp.append("<option value='05-35.html'><b>05-35</b> - ﻿गुणसाम्ये सदृशानाम् ॥३५॥</option>");
       $optgrp.append("<option value='05-36.html'><b>05-36</b> - ﻿द्वयधिकादि गुणानां तु ॥३६॥</option>");
       $optgrp.append("<option value='05-38.html'><b>05-38</b> - ﻿गुण-पर्ययवद् द्रव्यम् ॥३८॥</option>");
       $optgrp.append("<option value='05-40.html'><b>05-40</b> - ﻿सोऽनन्तसमय: ॥४०॥</option>");
       $optgrp.append("<option value='05-41.html'><b>05-41</b> - ﻿द्रव्याश्रया निर्गुणा गुणा: ॥४१॥</option>");
       $optgrp.append("<option value='05-42.html'><b>05-42</b> - ﻿तद्भाव: परिणाम: ॥४२॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿६-आस्रवाधिकार">')
       $optgrp.append("<option value='06-01.html'><b>06-01</b> - ﻿काय-वाङ्मन: कर्म-योग: ॥१॥</option>");
       $optgrp.append("<option value='06-02.html'><b>06-02</b> - ﻿स आस्रव: ॥२॥</option>");
       $optgrp.append("<option value='06-03.html'><b>06-03</b> - ﻿शुभ: पुण्यस्याशुभ: पापस्य ॥३॥</option>");
       $optgrp.append("<option value='06-04.html'><b>06-04</b> - ﻿सकषायाकषाययो: साम्परायिकेर्यापथयो: ॥४॥</option>");
       $optgrp.append("<option value='06-05.html'><b>06-05</b> - ﻿इन्द्रिय-कषायाव्रत-क्रिया: पंच-चतु:-पंच-पंचविंशति-संख्या: पूर्वस्य भेदा: ॥५॥</option>");
       $optgrp.append("<option value='06-06.html'><b>06-06</b> - ﻿तीव्र-मंद-ज्ञाताज्ञात-भावाधिकरण-वीर्य-विशेषेभ्यस्तद्विशेष: ॥६॥</option>");
       $optgrp.append("<option value='06-07.html'><b>06-07</b> - ﻿अधिकरणं जीवाजीवा: ॥७॥</option>");
       $optgrp.append("<option value='06-08.html'><b>06-08</b> - ﻿आद्यं संरम्भ-समारम्भारम्भयोग कृत-कारितानुमत-कषाय-विशेषैस्त्रिस्त्रिस्त्रि-श्चतुश्चैकश: ॥८॥</option>");
       $optgrp.append("<option value='06-10.html'><b>06-10</b> - ﻿तत्प्रदोष-निह्नव-मात्सर्यान्तरायासादनोपघाता ज्ञान-दर्शनावरणयो: ॥१०॥</option>");
       $optgrp.append("<option value='06-11.html'><b>06-11</b> - ﻿दु:ख-शोक-तापाक्रन्दन-वध-परिदेवनान्यात्म-परोभय-स्थानान्यसद्वेद्यस्य ॥११॥</option>");
       $optgrp.append("<option value='06-12.html'><b>06-12</b> - ﻿भूत-व्रत्यनुकम्पादान-सराग-संयमादि-योग: क्षांति: शौचमिति सद्वेद्यस्य ॥१२॥</option>");
       $optgrp.append("<option value='06-13.html'><b>06-13</b> - ﻿केवलि-श्रुत-संघ-धर्मदेवावर्णवादो दर्शनमोहस्य ॥१३॥</option>");
       $optgrp.append("<option value='06-14.html'><b>06-14</b> - ﻿कषायोदयात्तीव्र-परिणामश्चारित्र-मोहस्य ॥१४॥</option>");
       $optgrp.append("<option value='06-15.html'><b>06-15</b> - ﻿बह्वारम्भ-परिग्रहत्वं नारकस्यायुष: ॥१५॥</option>");
       $optgrp.append("<option value='06-16.html'><b>06-16</b> - ﻿माया तैर्यग्योनस्य ॥१६॥</option>");
       $optgrp.append("<option value='06-17.html'><b>06-17</b> - ﻿अल्पारम्भ परिग्रहत्वं मानुषस्य ॥१७॥</option>");
       $optgrp.append("<option value='06-18.html'><b>06-18</b> - ﻿स्वभाव-मार्दवं च ॥१८॥</option>");
       $optgrp.append("<option value='06-19.html'><b>06-19</b> - ﻿नि:शील-व्रतत्वं च सर्वेषाम् ॥१९॥</option>");
       $optgrp.append("<option value='06-20.html'><b>06-20</b> - ﻿सरागसंयम-संयमा-संयमाकामनिर्जराबालतपांसि दैवस्य ॥२०॥</option>");
       $optgrp.append("<option value='06-21.html'><b>06-21</b> - ﻿सम्यक्त्वं च ॥२१॥</option>");
       $optgrp.append("<option value='06-22.html'><b>06-22</b> - ﻿योगवक्रता विसंवादनं चाशुभस्य नाम्न: ॥२२॥</option>");
       $optgrp.append("<option value='06-23.html'><b>06-23</b> - ﻿तद्विपरीतं शुभस्य ॥२३॥</option>");
       $optgrp.append("<option value='06-24.html'><b>06-24</b> - ﻿दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य ॥२४॥</option>");
       $optgrp.append("<option value='06-25.html'><b>06-25</b> - ﻿परात्म-निन्दा-प्रशंसे सदसद् गुणोच्छादनोद्भावने च नीचैर्गोत्रस्य ॥२५॥</option>");
       $optgrp.append("<option value='06-26.html'><b>06-26</b> - ﻿तद्विपर्ययो नीचैर्वृत्त्यनुत्सेकौ चोत्तरस्य ॥२६॥</option>");
       $optgrp.append("<option value='06-27.html'><b>06-27</b> - ﻿विघ्नकरणमन्तरायस्य ॥२७॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿७-आस्रवाधिकार">')
       $optgrp.append("<option value='07-01.html'><b>07-01</b> - ﻿हिंसाऽनृत-स्तेयाब्रह्म-परिग्रहेभ्यो विरतिर्व्रतम् ॥१॥</option>");
       $optgrp.append("<option value='07-02.html'><b>07-02</b> - ﻿देश सर्वतोऽणु-महती ॥२॥</option>");
       $optgrp.append("<option value='07-03.html'><b>07-03</b> - ﻿तत्स्थैर्यार्थं भावना: पञ्च-पञ्च ॥३॥</option>");
       $optgrp.append("<option value='07-04.html'><b>07-04</b> - ﻿वाङ्मनोगुप्तीर्यादाननिक्षेपण-समित्यालोकित-पान-भोजनानि पञ्च ॥४॥</option>");
       $optgrp.append("<option value='07-05.html'><b>07-05</b> - ﻿क्रोध-लोभ-भीरुत्व-हास्य-प्रत्याख्यानान्यनुवीचि-भाषणं च पञ्च ॥५॥</option>");
       $optgrp.append("<option value='07-06.html'><b>07-06</b> - ﻿शून्यागार-विमोचितावास-परोपरोधाकरण-भैक्ष्यशुद्धि-सधर्मावि-संवादा: पञ्च ॥६॥</option>");
       $optgrp.append("<option value='07-07.html'><b>07-07</b> - ﻿स्त्रीरागकथा श्रवण-तन्मनोहरांग निरीक्षण पूर्व-रतानुस्मरण-वृष्येष्टरस-स्वशरीरसंस्कारत्यागा: पञ्च ॥७॥</option>");
       $optgrp.append("<option value='07-08.html'><b>07-08</b> - ﻿मनोज्ञामनोज्ञेन्द्रिय-विषय-राग-द्वेष वर्जनानि पञ्च ॥८॥</option>");
       $optgrp.append("<option value='07-09.html'><b>07-09</b> - ﻿हिंसादिष्विहामुत्रापायावद्यदर्शनम् ॥९॥</option>");
       $optgrp.append("<option value='07-10.html'><b>07-10</b> - ﻿दु:खमेव वा ॥१०॥</option>");
       $optgrp.append("<option value='07-11.html'><b>07-11</b> - ﻿मैत्री-प्रमोद-कारुण्य-माध्यस्थानि च सत्त्व-गुणाधिक-क्लिश्यमानाविनयेषु ॥११॥</option>");
       $optgrp.append("<option value='07-12.html'><b>07-12</b> - ﻿जगत्काय-स्वभावौ वा संवेगवैराग्यार्थम् ॥१२॥</option>");
       $optgrp.append("<option value='07-13.html'><b>07-13</b> - ﻿प्रमत्तयोगात्प्राण-व्यपरोपणं हिंसा ॥१३॥</option>");
       $optgrp.append("<option value='07-14.html'><b>07-14</b> - ﻿असदभिधानमनृतम् ॥१४॥</option>");
       $optgrp.append("<option value='07-15.html'><b>07-15</b> - ﻿अदत्तादानं स्तेयम् ॥१५॥</option>");
       $optgrp.append("<option value='07-16.html'><b>07-16</b> - ﻿मैथुनम-ब्रह्म ॥१६॥</option>");
       $optgrp.append("<option value='07-17.html'><b>07-17</b> - ﻿मूर्च्छा परिग्रह: ॥१७॥</option>");
       $optgrp.append("<option value='07-18.html'><b>07-18</b> - ﻿नि:शल्यो व्रती ॥१८॥</option>");
       $optgrp.append("<option value='07-19.html'><b>07-19</b> - ﻿अगार्यनगारश्च ॥१९॥</option>");
       $optgrp.append("<option value='07-20.html'><b>07-20</b> - ﻿अणुव्रतोऽगारी ॥२०॥</option>");
       $optgrp.append("<option value='07-21.html'><b>07-21</b> - ﻿दिग्देशानर्थदण्ड-विरति-सामायिक-प्रोषधोपवासोपभोग-परिभोग-परिमाणातिथि-संविभागव्रतसम्पन्नश्च ॥२१॥</option>");
       $optgrp.append("<option value='07-22.html'><b>07-22</b> - ﻿मारणान्तिकीं सल्लेखनां जोषिता ॥२२॥</option>");
       $optgrp.append("<option value='07-23.html'><b>07-23</b> - ﻿शंका-कांक्षाविचिकित्सान्यदृष्टि-प्रशंसा-संस्तवा: सम्यग्दृष्टेरती-चारा: ॥२३॥</option>");
       $optgrp.append("<option value='07-24.html'><b>07-24</b> - ﻿व्रत-शीलेषु पञ्च पञ्च यथाक्रमम् ॥२४॥</option>");
       $optgrp.append("<option value='07-25.html'><b>07-25</b> - ﻿बंधवध-च्छेदाति-भारारोपणान्नपान-निरोधा: ॥२५॥</option>");
       $optgrp.append("<option value='07-26.html'><b>07-26</b> - ﻿मिथ्योपदेश-रहोभ्याख्यान-कूटलेखक्रिया-न्यासापहार-साकारमन्त्रभेदा: ॥२६॥</option>");
       $optgrp.append("<option value='07-27.html'><b>07-27</b> - ﻿स्तेनप्रयोग-तदाहृतादानविरुद्धराज्यातिक्रम-हीनाधिकमानोन्मान-प्रतिरूपक-व्यवहारा: ॥२७॥</option>");
       $optgrp.append("<option value='07-28.html'><b>07-28</b> - ﻿परविवाह करणेत्वरिका-परिगृहीतापरिगृहीता-गमनानङ्गक्रीडा-कामतीव्राभिनिवेशा: ॥२८॥</option>");
       $optgrp.append("<option value='07-29.html'><b>07-29</b> - ﻿क्षेत्रवास्तु-हिरण्यसुवर्ण-धन-धान्य-दासीदास-कुप्य-प्रमाणातिक्रमा: ॥२९॥</option>");
       $optgrp.append("<option value='07-30.html'><b>07-30</b> - ﻿ऊर्ध्वाधस्तिर्यग्व्यतिक्रमक्षेत्रवृद्धि-स्मृत्यंतराधानानि ॥३०॥</option>");
       $optgrp.append("<option value='07-31.html'><b>07-31</b> - ﻿आनयन-प्रेष्यप्रयोग-शब्दरूपानुपात-पुद्गलक्षेपा: ॥३१॥</option>");
       $optgrp.append("<option value='07-32.html'><b>07-32</b> - ﻿कन्दर्प-कौत्कुच्य-मौखर्यासमीक्ष्याधि-करणोपभोगपरिभोगानर्थक्यानि ॥३२॥</option>");
       $optgrp.append("<option value='07-33.html'><b>07-33</b> - ﻿योग दु:प्रणिधानानादर-स्मृत्यनु-पस्थानानि ॥३३॥</option>");
       $optgrp.append("<option value='07-34.html'><b>07-34</b> - ﻿अप्रत्यवेक्षिताप्रमार्जितोत्सर्गादानसंस्तरोपक्रमणा-नादरस्मृत्यनुप-स्थानानि ॥३४॥</option>");
       $optgrp.append("<option value='07-35.html'><b>07-35</b> - ﻿सचित्त-संबंधसम्मिश्रा-भिषवदु:पक्वाहारा: ॥३५॥</option>");
       $optgrp.append("<option value='07-36.html'><b>07-36</b> - ﻿सचित्त-निक्षेपापिधानपरव्यपदेश-मात्सर्यकालातिक्रमा: ॥३६॥</option>");
       $optgrp.append("<option value='07-37.html'><b>07-37</b> - ﻿जीवित-मरणाशंसा-मित्रानुराग-सुखानुबंध-निदानानि ॥३७॥</option>");
       $optgrp.append("<option value='07-38.html'><b>07-38</b> - ﻿अनुग्रहार्थं स्वस्यातिसर्गो दानम् ॥३८॥</option>");
       $optgrp.append("<option value='07-39.html'><b>07-39</b> - ﻿विधि-द्रव्य-दातृ-पात्र-विशेषात्तद्विशेष: ॥३९॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿८-बंधाधिकार">')
       $optgrp.append("<option value='08-01.html'><b>08-01</b> - ﻿मिथ्यादर्शनाविरति-प्रमाद-कषाय-योगा बन्धहेतव: ॥१॥</option>");
       $optgrp.append("<option value='08-02.html'><b>08-02</b> - ﻿सकषायत्वाज्जीव: कर्मणो योग्यान् पुद्गलानादत्ते स बंध: ॥२॥</option>");
       $optgrp.append("<option value='08-03.html'><b>08-03</b> - ﻿प्रकृति स्थित्यनुभव-प्रदेशास्तद्विधय: ॥३॥</option>");
       $optgrp.append("<option value='08-04.html'><b>08-04</b> - ﻿आद्यो ज्ञान-दर्शनावरणवेदनीय-मोहनीयायुर्नाम-गोत्रान्तराया: ॥४॥</option>");
       $optgrp.append("<option value='08-05.html'><b>08-05</b> - ﻿पञ्च-नव-द्वयष्टाविंशति-चतुर्-द्विचत्वारिंशद्-द्वि-पञ्च-भेदा-यथाक्रमम् ॥५॥</option>");
       $optgrp.append("<option value='08-06.html'><b>08-06</b> - ﻿मतिश्रुतावधि-मन:पर्यय केवलानाम् ॥६॥</option>");
       $optgrp.append("<option value='08-07.html'><b>08-07</b> - ﻿चक्षुरचक्षुरवधिकेवलानां निद्रा-निद्रानिद्रा-प्रचला-प्रचलाप्रचला-स्त्यानगृद्धयश्च ॥७॥</option>");
       $optgrp.append("<option value='08-08.html'><b>08-08</b> - ﻿सदसद्वेद्ये ॥८॥</option>");
       $optgrp.append("<option value='08-09.html'><b>08-09</b> - ﻿दर्शनचारित्र-मोहनीयाकषाय-कषायवेदनीयाख्यास्त्रिद्वि-नव-षोडशभेदा: सम्यक्त्व-मिथ्यात्व-तदुभयान्यकषाय-कषायौ हास्यरत्यरति-शोक-भय-जुगुप्सा-स्त्री-पुन्नपुंसक-वेदा अनन्तानुबंध्य-प्रत्याख्यान-प्रत्याख्यान-संज्वलन-विकल्पाश्चैकश: क्रोध-मान-माया-लोभा: ॥९॥</option>");
       $optgrp.append("<option value='08-10.html'><b>08-10</b> - ﻿नारकतैर्यग्योन-मानुष-दैवानि ॥१०॥</option>");
       $optgrp.append("<option value='08-11.html'><b>08-11</b> - ﻿गति-जाति-शरीराङ्गोपाङ्गनिर्माण-बंधन-संघात-संस्थान-संहनन-स्पर्श-रस-गंध-वर्णानुपूर्व्यागुरुलघूपघात-परघातातपोद्योतोच्छ्वास-विहायोगतय: प्रत्येक-शरीर-त्रस-सुभग-सुस्वर-शुभ-सूक्ष्म-पर्याप्ति-स्थिरादेय यश: कीर्ति-सेतराणि तीर्थकरत्वं च ॥११॥</option>");
       $optgrp.append("<option value='08-12.html'><b>08-12</b> - ﻿उच्चैर्नीचैश्च ॥१२॥</option>");
       $optgrp.append("<option value='08-13.html'><b>08-13</b> - ﻿दान-लाभ-भोगोपभोग-वीर्याणाम् ॥१३॥</option>");
       $optgrp.append("<option value='08-14.html'><b>08-14</b> - ﻿आदितस्तिसृणा-मंतरायस्य च त्रिंशत्सागरोपमकोटीकोट्य: परा स्थिति: ॥१४॥</option>");
       $optgrp.append("<option value='08-15.html'><b>08-15</b> - ﻿सप्तति-र्मोहनीयस्य ॥१५॥</option>");
       $optgrp.append("<option value='08-16.html'><b>08-16</b> - ﻿विंशतिर्नाम-गोत्रयो: ॥११६॥</option>");
       $optgrp.append("<option value='08-17.html'><b>08-17</b> - ﻿त्रयस्त्रिंशत्सागरोपमाण्यायुष: ॥१७॥</option>");
       $optgrp.append("<option value='08-18.html'><b>08-18</b> - ﻿अपरा द्वादश मुहूर्ता वेदनीयस्य ॥१८॥</option>");
       $optgrp.append("<option value='08-19.html'><b>08-19</b> - ﻿नाम-गोत्रयोरष्टौ ॥१९॥</option>");
       $optgrp.append("<option value='08-20.html'><b>08-20</b> - ﻿शेषाणामन्तर्मुहूर्ता ॥२०॥</option>");
       $optgrp.append("<option value='08-21.html'><b>08-21</b> - ﻿विपाकोऽनुभव: ॥२१॥</option>");
       $optgrp.append("<option value='08-22.html'><b>08-22</b> - ﻿स यथानाम् ॥२२॥</option>");
       $optgrp.append("<option value='08-23.html'><b>08-23</b> - ﻿ततश्च निर्जरा ॥२३॥</option>");
       $optgrp.append("<option value='08-24.html'><b>08-24</b> - ﻿नाम-प्रत्यया: सर्वतो योग-विशेषात्-सूक्ष्मैकक्षेत्रावगाह-स्थिता: सर्वात्म-प्रदेशेष्वनन्तानन्त-प्रदेशा: ॥२४॥</option>");
       $optgrp.append("<option value='08-25.html'><b>08-25</b> - ﻿सद्वेद्यशुभायुर्नाम-गोत्राणि पुण्यम् ॥२५॥</option>");
       $optgrp.append("<option value='08-26.html'><b>08-26</b> - ﻿अतोऽन्यत्पापम् ॥२६॥</option>");
       $optgrp.append("<option value='09 miss.html'><b>09 miss</b></option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿९-संवर-निर्जराधिकार">')
       $optgrp.append("<option value='09-01.html'><b>09-01</b> - ﻿आस्रव-निरोध: संवर: ॥१॥</option>");
       $optgrp.append("<option value='09-02.html'><b>09-02</b> - ﻿स गुप्ति-समिति-धर्मानुप्रेक्षा-परीषहजय-चारित्रै: ॥२॥</option>");
       $optgrp.append("<option value='09-03.html'><b>09-03</b> - ﻿तपसा निर्जरा च ॥३॥</option>");
       $optgrp.append("<option value='09-04.html'><b>09-04</b> - ﻿सम्यग्योगनिग्रहो गुप्ति: ॥४॥</option>");
       $optgrp.append("<option value='09-05.html'><b>09-05</b> - ﻿ईर्याभाषैषणा-दाननिक्षेपोत्सर्गा: समितय: ॥५॥</option>");
       $optgrp.append("<option value='09-06.html'><b>09-06</b> - ﻿उत्तमक्षमा-मार्दवार्जव-सत्य-शौच-संयमतपस्त्यागा-किञ्चन्य-ब्रह्मचर्याणि धर्म: ॥६॥</option>");
       $optgrp.append("<option value='09-07.html'><b>09-07</b> - ﻿अनित्याशरण-संसारैकत्वान्य-त्वाशुच्यास्रवसंवर-निर्जरा-लोक-बोधिदुर्लभ-धर्म-स्वाख्यातत्त्वानु-चिन्तन-मनुप्रेक्षा: ॥७॥</option>");
       $optgrp.append("<option value='09-08.html'><b>09-08</b> - ﻿मार्गाच्यवन-निर्जरार्थं परिषोढव्या: परीषहा: ॥८॥</option>");
       $optgrp.append("<option value='09-09.html'><b>09-09</b> - ﻿क्षुत्पिपासा-शीतोष्णदंश-मशक-नाग्न्यारति-स्त्री-चर्या-निषद्या-शय्याक्रोशवधयाचनालाभ-रोग-तृणस्पर्श-मल-सत्कारपुरस्कार-प्रज्ञाज्ञानादर्शनानि ॥९॥</option>");
       $optgrp.append("<option value='09-10.html'><b>09-10</b> - ﻿सूक्ष्मसाम्पराय-छद्मस्थवीत-रागयोश्चतुर्दश ॥१०॥</option>");
       $optgrp.append("<option value='09-11.html'><b>09-11</b> - ﻿एकादश जिने ॥११॥</option>");
       $optgrp.append("<option value='09-12.html'><b>09-12</b> - ﻿बादर-साम्पराये सर्वे ॥१२॥</option>");
       $optgrp.append("<option value='09-13.html'><b>09-13</b> - ﻿ज्ञानावरणे प्रज्ञाज्ञाने ॥१३॥</option>");
       $optgrp.append("<option value='09-14.html'><b>09-14</b> - ﻿दर्शन-मोहान्तराययोरदर्शनालाभौ ॥१४॥</option>");
       $optgrp.append("<option value='09-15.html'><b>09-15</b> - ﻿चारित्रमोहे नाग्न्यारति-स्त्री-निषद्या-क्रोश-याचना-सत्कारपुरस्कारा: ॥१५॥</option>");
       $optgrp.append("<option value='09-16.html'><b>09-16</b> - ﻿वेदनीये शेषा: ॥१६॥</option>");
       $optgrp.append("<option value='09-17.html'><b>09-17</b> - ﻿एकादयो भाज्या युगपदेक-स्मिन्नैकोनविंशते: ॥१७॥</option>");
       $optgrp.append("<option value='09-18.html'><b>09-18</b> - ﻿सामायिकच्छेदोपस्थापना-परिहारविशुद्धि-सूक्ष्मसाम्पराय-यथाख्यात-मितिचारित्रम् ॥१८॥</option>");
       $optgrp.append("<option value='09-19.html'><b>09-19</b> - ﻿अनशनावमौदर्य-वृत्तिपरिसंख्यान-रस-परित्याग-विविक्तशय्यासन-कायक्लेशा बाह्यं तप: ॥१९॥</option>");
       $optgrp.append("<option value='09-20.html'><b>09-20</b> - ﻿प्रायश्चित्त-विनय-वैयावृत्त्य-स्वाध्याय-व्युत्सर्ग-ध्यानान्युत्तरम् ॥२०॥</option>");
       $optgrp.append("<option value='09-21.html'><b>09-21</b> - ﻿नवचतुर्दश-पञ्च द्विभेदा यथाक्रमं प्राग्ध्यानात् ॥२१॥</option>");
       $optgrp.append("<option value='09-22.html'><b>09-22</b> - ﻿आलोचना-प्रतिक्रमण-तदुभय-विवेक-व्युत्सर्ग-तपश्छेदपरिहारो-पस्थापना: ॥२२॥</option>");
       $optgrp.append("<option value='09-23.html'><b>09-23</b> - ﻿ज्ञान-दर्शन-चारित्रोपचारा: ॥२३॥</option>");
       $optgrp.append("<option value='09-24.html'><b>09-24</b> - ﻿आचार्योपाध्याय-तपस्वि-शैक्ष्य-ग्लान-गण-कुल-संघ-साधु-मनोज्ञानाम् ॥२४॥</option>");
       $optgrp.append("<option value='09-25.html'><b>09-25</b> - ﻿वाचना-पृच्छनानुप्रेक्षाम्नाय-धर्मोपदेशा: ॥२५॥</option>");
       $optgrp.append("<option value='09-26.html'><b>09-26</b> - ﻿बाह्याभ्यन्तरोपध्यो: ॥२६॥</option>");
       $optgrp.append("<option value='09-27.html'><b>09-27</b> - ﻿उत्तम-संहननस्यैकाग्र-चिन्ता-निरोधो ध्यानमान्त-र्मुहूर्तात्॥२७॥</option>");
       $optgrp.append("<option value='09-28.html'><b>09-28</b> - ﻿आर्त्त-रौद्र-धर्म्य-शुक्लानि ॥२८॥</option>");
       $optgrp.append("<option value='09-29.html'><b>09-29</b> - ﻿परे मोक्षहेतू ॥२९॥</option>");
       $optgrp.append("<option value='09-30.html'><b>09-30</b> - ﻿आर्तममनोज्ञस्य संप्रयोगे तद्विप्रयोगाय स्मृति-समन्वाहार: ॥३०॥</option>");
       $optgrp.append("<option value='09-31.html'><b>09-31</b> - ﻿विपरीतं मनोज्ञस्य ॥३१॥</option>");
       $optgrp.append("<option value='09-32.html'><b>09-32</b> - ﻿वेदनायाश्च ॥३२॥</option>");
       $optgrp.append("<option value='09-33.html'><b>09-33</b> - ﻿निदानं च ॥३३॥</option>");
       $optgrp.append("<option value='09-34.html'><b>09-34</b> - ﻿तदविरतदेशविरतप्रमत्तसंयतानां ॥३४॥</option>");
       $optgrp.append("<option value='09-35.html'><b>09-35</b> - ﻿हिंसानृत-स्तेय-विषयसंरक्षणेभ्यो रौद्रमविरत-देशविरतयो: ॥३५॥</option>");
       $optgrp.append("<option value='09-36.html'><b>09-36</b> - ﻿आज्ञापाय-विपाक-संस्थान-विचयाय धर्म्यम् ॥३६॥</option>");
       $optgrp.append("<option value='09-37.html'><b>09-37</b> - ﻿शुक्ले चाद्ये पूर्व-विद:॥३७॥</option>");
       $optgrp.append("<option value='09-38.html'><b>09-38</b> - ﻿परे केवलिन: ॥३८॥</option>");
       $optgrp.append("<option value='09-39.html'><b>09-39</b> - ﻿पृथक्त्वैकत्व-वितर्क-सूक्ष्मक्रिया-प्रतिपाति-व्युपरत-क्रिर्यानिवर्तीनि ॥३९॥</option>");
       $optgrp.append("<option value='09-40.html'><b>09-40</b> - ﻿त्र्येकयोग-काययोगायोगानाम् ॥४०॥</option>");
       $optgrp.append("<option value='09-41.html'><b>09-41</b> - ﻿एकाश्रये सवितर्कवीचारे पूर्वे ॥४१॥</option>");
       $optgrp.append("<option value='09-42.html'><b>09-42</b> - ﻿अवीचारं द्वितीयम् ॥४२॥</option>");
       $optgrp.append("<option value='09-43.html'><b>09-43</b> - ﻿वितर्क: श्रुतम् ॥४३॥</option>");
       $optgrp.append("<option value='09-44.html'><b>09-44</b> - ﻿वीचारोऽर्थव्यंजन-योगसंक्रान्ति: ॥४४॥</option>");
       $optgrp.append("<option value='09-45.html'><b>09-45</b> - ﻿सम्यग्दृष्टि-श्रावक-विरता-नन्तवियोजक-दर्शनमोह-क्षपकोपशम-कोपशांत-मोहक्षपक-क्षीणमोह-जिना: क्रमशोऽसंख्येय-गुण-निर्जरा: ॥४५॥</option>");
       $optgrp.append("<option value='09-46.html'><b>09-46</b> - ﻿पुलाक-वकुश-कुशील-निर्ग्रन्थ-स्नातका निर्ग्रंथा: ॥४६॥</option>");
       $optgrp.append("<option value='09-47.html'><b>09-47</b> - ﻿संयम-श्रुत-प्रतिसेवना-तीर्थलिङ्ग-लेश्योपपाद-स्थान-विकल्पत: साध्या: ॥४७॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿१०-मोक्षाधिकार">')
       $optgrp.append("<option value='10-01.html'><b>10-01</b> - ﻿मोहक्षयाज्ज्ञान-दर्शनावरणान्तराय-क्षयाच्च केवलम् ॥१॥</option>");
       $optgrp.append("<option value='10-02.html'><b>10-02</b> - ﻿बन्धहेत्वभाव-निर्जराभ्यां कृत्स्न-कर्म-विप्रमोक्षो मोक्ष: ॥२॥</option>");
       $optgrp.append("<option value='10-03.html'><b>10-03</b> - ﻿औपशमिकादि-भव्यत्वानां च ॥३॥</option>");
       $optgrp.append("<option value='10-04.html'><b>10-04</b> - ﻿अन्यत्र केवलसम्यक्त्व-ज्ञान-दर्शन-सिद्धत्वेभ्य: ॥४॥</option>");
       $optgrp.append("<option value='10-05.html'><b>10-05</b> - ﻿तदनन्तरमूर्ध्वं गच्छत्या-लोकान्तात् ॥५॥</option>");
       $optgrp.append("<option value='10-06.html'><b>10-06</b> - ﻿पूर्वप्रयोगादसङ्गत्वाद्-बन्धच्छेदात्तथागतिपरिणामाच्च ॥६॥</option>");
       $optgrp.append("<option value='10-07.html'><b>10-07</b> - ﻿आविद्धकुलालचक्रवद्-व्यपगतलेपालाबुवदेरण्डबीजवदग्निशिखावच्च ॥७॥</option>");
       $optgrp.append("<option value='10-08.html'><b>10-08</b> - ﻿धर्मास्तिकायाभावात् ॥८॥</option>");
       $optgrp.append("<option value='10-09.html'><b>10-09</b> - ﻿क्षेत्र-काल-गति-लिङ्ग-तीर्थचारित्र-प्रत्येकबुद्धबोधित-ज्ञानावगाहनान्तर-संख्याल्पबहुत्वत: साध्या: ॥९॥</option>");
       $optgrp.append("<option value='37 miss.html'><b>37 miss</b></option>");
       $optgrp.append("<option value='39 miss.html'><b>39 miss</b></option>");
    mySel.append($optgrp);
  mySel.selectmenu();
  mySel.selectmenu('refresh', true);
})
$( document ).ready(function() {
  mySel=$('select#select-native-1')
    $optgrp=$('<optgroup label="﻿१-जीवाधिकार">')
       $optgrp.append("<option value='01-01.html'><b>01-01</b> - ﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः ॥१॥</option>");
       $optgrp.append("<option value='01-02.html'><b>01-02</b> - ﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम् ॥२॥</option>");
       $optgrp.append("<option value='01-06.html'><b>01-06</b> - ﻿प्रमाणनयैरधिगमः ॥६॥</option>");
       $optgrp.append("<option value='01-08.html'><b>01-08</b> - ﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च ॥८॥</option>");
       $optgrp.append("<option value='01-09.html'><b>01-09</b> - ﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम् ॥९॥</option>");
       $optgrp.append("<option value='01-12.html'><b>01-12</b> - ﻿प्रत्यक्षमन्यत् ॥१२॥</option>");
       $optgrp.append("<option value='01-20.html'><b>01-20</b> - ﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌ ॥२०॥</option>");
       $optgrp.append("<option value='01-30.html'><b>01-30</b> - ﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः ॥३०॥</option>");
       $optgrp.append("<option value='02-07.html'><b>02-07</b> - ﻿जीवभव्याभव्यत्वानि च ॥७॥</option>");
       $optgrp.append("<option value='02-08.html'><b>02-08</b> - ﻿उपयोगो लक्षणम् ॥८॥</option>");
       $optgrp.append("<option value='02-15.html'><b>02-15</b> - ﻿पंचेद्रियाणि ॥१५॥</option>");
       $optgrp.append("<option value='02-18.html'><b>02-18</b> - ﻿लब्ध्युपयोगो भावेन्द्रियम् ॥१८॥</option>");
       $optgrp.append("<option value='02-22.html'><b>02-22</b> - ﻿वनस्पत्यन्तानामेकम् ॥२२॥</option>");
       $optgrp.append("<option value='02-33.html'><b>02-33</b> - ﻿जरायुजाण्डजपोतानां गर्भः ॥३३॥</option>");
       $optgrp.append("<option value='02-49.html'><b>02-49</b> - ﻿शुभं विशुद्धमव्याघाति चाहारकं प्रमत्तसंयतस्यैव ॥४९॥</option>");
       $optgrp.append("<option value='02-53.html'><b>02-53</b> - ﻿औपपादिक चरमोत्तम-देहाऽसंख्येय-वर्षायुषोऽनपवर्त्यायुषः ॥५३॥</option>");
       $optgrp.append("<option value='03-38.html'><b>03-38</b> - ﻿नृस्थितीपरावरे त्रिपल्योपमान्तर्मुहूर्ते॥३८॥</option>");
       $optgrp.append("<option value='04-42.html'><b>04-42</b> - ﻿लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम् ॥४२॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿५-अजीवाधिकार">')
       $optgrp.append("<option value='05-01.html'><b>05-01</b> - ﻿अजीव-काया-धर्माधर्माकाश-पुद्गला: ॥१॥</option>");
       $optgrp.append("<option value='05-02.html'><b>05-02</b> - ﻿द्रव्याणि ॥२॥</option>");
       $optgrp.append("<option value='05-08.html'><b>05-08</b> - ﻿असंख्येया: प्रदेशा धर्माधर्मैकजीवानाम् ॥८॥</option>");
       $optgrp.append("<option value='05-09.html'><b>05-09</b> - ﻿आकाशस्यानन्ता: ॥९॥</option>");
       $optgrp.append("<option value='05-19.html'><b>05-19</b> - ﻿शरीरवाङ्मन:-प्राणापाना पुद्गलानाम् ॥१९॥</option>");
       $optgrp.append("<option value='05-22.html'><b>05-22</b> - ﻿वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य ॥२२॥</option>");
       $optgrp.append("<option value='05-25.html'><b>05-25</b> - ﻿अणव: स्कन्धाश्च ॥२५॥</option>");
       $optgrp.append("<option value='06-02.html'><b>06-02</b> - ﻿स आस्रव: ॥२॥</option>");
       $optgrp.append("<option value='06-24.html'><b>06-24</b> - ﻿दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य ॥२४॥</option>");
       $optgrp.append("<option value='07-05.html'><b>07-05</b> - ﻿क्रोध-लोभ-भीरुत्व-हास्य-प्रत्याख्यानान्यनुवीचि-भाषणं च पञ्च ॥५॥</option>");
       $optgrp.append("<option value='07-14.html'><b>07-14</b> - ﻿असदभिधानमनृतम् ॥१४॥</option>");
       $optgrp.append("<option value='07-22.html'><b>07-22</b> - ﻿मारणान्तिकीं सल्लेखनां जोषिता ॥२२॥</option>");
       $optgrp.append("<option value='07-23.html'><b>07-23</b> - ﻿शंका-कांक्षाविचिकित्सान्यदृष्टि-प्रशंसा-संस्तवा: सम्यग्दृष्टेरती-चारा: ॥२३॥</option>");
       $optgrp.append("<option value='07-27.html'><b>07-27</b> - ﻿स्तेनप्रयोग-तदाहृतादानविरुद्धराज्यातिक्रम-हीनाधिकमानोन्मान-प्रतिरूपक-व्यवहारा: ॥२७॥</option>");
       $optgrp.append("<option value='07-28.html'><b>07-28</b> - ﻿परविवाह करणेत्वरिका-परिगृहीतापरिगृहीता-गमनानङ्गक्रीडा-कामतीव्राभिनिवेशा: ॥२८॥</option>");
       $optgrp.append("<option value='07-29.html'><b>07-29</b> - ﻿क्षेत्रवास्तु-हिरण्यसुवर्ण-धन-धान्य-दासीदास-कुप्य-प्रमाणातिक्रमा: ॥२९॥</option>");
       $optgrp.append("<option value='07-30.html'><b>07-30</b> - ﻿ऊर्ध्वाधस्तिर्यग्व्यतिक्रमक्षेत्रवृद्धि-स्मृत्यंतराधानानि ॥३०॥</option>");
       $optgrp.append("<option value='07-31.html'><b>07-31</b> - ﻿आनयन-प्रेष्यप्रयोग-शब्दरूपानुपात-पुद्गलक्षेपा: ॥३१॥</option>");
       $optgrp.append("<option value='07-32.html'><b>07-32</b> - ﻿कन्दर्प-कौत्कुच्य-मौखर्यासमीक्ष्याधि-करणोपभोगपरिभोगानर्थक्यानि ॥३२॥</option>");
       $optgrp.append("<option value='07-36.html'><b>07-36</b> - ﻿सचित्त-निक्षेपापिधानपरव्यपदेश-मात्सर्यकालातिक्रमा: ॥३६॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿८-बंधाधिकार">')
       $optgrp.append("<option value='08-01.html'><b>08-01</b> - ﻿मिथ्यादर्शनाविरति-प्रमाद-कषाय-योगा बन्धहेतव: ॥१॥</option>");
       $optgrp.append("<option value='08-06.html'><b>08-06</b> - ﻿मतिश्रुतावधि-मन:पर्यय केवलानाम् ॥६॥</option>");
       $optgrp.append("<option value='08-09.html'><b>08-09</b> - ﻿दर्शनचारित्र-मोहनीयाकषाय-कषायवेदनीयाख्यास्त्रिद्वि-नव-षोडशभेदा: सम्यक्त्व-मिथ्यात्व-तदुभयान्यकषाय-कषायौ हास्यरत्यरति-शोक-भय-जुगुप्सा-स्त्री-पुन्नपुंसक-वेदा अनन्तानुबंध्य-प्रत्याख्यान-प्रत्याख्यान-संज्वलन-विकल्पाश्चैकश: क्रोध-मान-माया-लोभा: ॥९॥</option>");
       $optgrp.append("<option value='08-11.html'><b>08-11</b> - ﻿गति-जाति-शरीराङ्गोपाङ्गनिर्माण-बंधन-संघात-संस्थान-संहनन-स्पर्श-रस-गंध-वर्णानुपूर्व्यागुरुलघूपघात-परघातातपोद्योतोच्छ्वास-विहायोगतय: प्रत्येक-शरीर-त्रस-सुभग-सुस्वर-शुभ-सूक्ष्म-पर्याप्ति-स्थिरादेय यश: कीर्ति-सेतराणि तीर्थकरत्वं च ॥११॥</option>");
       $optgrp.append("<option value='09-03.html'><b>09-03</b> - ﻿तपसा निर्जरा च ॥३॥</option>");
       $optgrp.append("<option value='09-07.html'><b>09-07</b> - ﻿अनित्याशरण-संसारैकत्वान्य-त्वाशुच्यास्रवसंवर-निर्जरा-लोक-बोधिदुर्लभ-धर्म-स्वाख्यातत्त्वानु-चिन्तन-मनुप्रेक्षा: ॥७॥</option>");
       $optgrp.append("<option value='09-09.html'><b>09-09</b> - ﻿क्षुत्पिपासा-शीतोष्णदंश-मशक-नाग्न्यारति-स्त्री-चर्या-निषद्या-शय्याक्रोशवधयाचनालाभ-रोग-तृणस्पर्श-मल-सत्कारपुरस्कार-प्रज्ञाज्ञानादर्शनानि ॥९॥</option>");
       $optgrp.append("<option value='09-11.html'><b>09-11</b> - ﻿एकादश जिने ॥११॥</option>");
       $optgrp.append("<option value='09-22.html'><b>09-22</b> - ﻿आलोचना-प्रतिक्रमण-तदुभय-विवेक-व्युत्सर्ग-तपश्छेदपरिहारो-पस्थापना: ॥२२॥</option>");
       $optgrp.append("<option value='09-23.html'><b>09-23</b> - ﻿ज्ञान-दर्शन-चारित्रोपचारा: ॥२३॥</option>");
       $optgrp.append("<option value='09-27.html'><b>09-27</b> - ﻿उत्तम-संहननस्यैकाग्र-चिन्ता-निरोधो ध्यानमान्त-र्मुहूर्तात्॥२७॥</option>");
       $optgrp.append("<option value='09-36.html'><b>09-36</b> - ﻿आज्ञापाय-विपाक-संस्थान-विचयाय धर्म्यम् ॥३६॥</option>");
       $optgrp.append("<option value='09-37.html'><b>09-37</b> - ﻿शुक्ले चाद्ये पूर्व-विद:॥३७॥</option>");
       $optgrp.append("<option value='09-38.html'><b>09-38</b> - ﻿परे केवलिन: ॥३८॥</option>");
       $optgrp.append("<option value='09-39.html'><b>09-39</b> - ﻿पृथक्त्वैकत्व-वितर्क-सूक्ष्मक्रिया-प्रतिपाति-व्युपरत-क्रिर्यानिवर्तीनि ॥३९॥</option>");
       $optgrp.append("<option value='09-40.html'><b>09-40</b> - ﻿त्र्येकयोग-काययोगायोगानाम् ॥४०॥</option>");
       $optgrp.append("<option value='09-45.html'><b>09-45</b> - ﻿सम्यग्दृष्टि-श्रावक-विरता-नन्तवियोजक-दर्शनमोह-क्षपकोपशम-कोपशांत-मोहक्षपक-क्षीणमोह-जिना: क्रमशोऽसंख्येय-गुण-निर्जरा: ॥४५॥</option>");
       $optgrp.append("<option value='10-09.html'><b>10-09</b> - ﻿क्षेत्र-काल-गति-लिङ्ग-तीर्थचारित्र-प्रत्येकबुद्धबोधित-ज्ञानावगाहनान्तर-संख्याल्पबहुत्वत: साध्या: ॥९॥</option>");
    mySel.append($optgrp);
  mySel.selectmenu();
  mySel.selectmenu('refresh', true);
})
