document.write("<div id=आर्यिका-ज्ञानमती class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿देवों की पूजा आदि से आप महान नहीं हैं</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿विग्रह आदि महोदय से भी आप महान नहीं हैं</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿तीर्थंकरत्व हेतु से भी आप महान नहीं हैं</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿दोषों तथा आवरणों का पूर्णतया अभाव संभव है</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿सर्वज्ञ की व्यवस्था</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿आप ही निर्दोष सर्वज्ञ हैं</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿सर्वथा एकांतवाद प्रमाण से बाधित है</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿एकांत में शुभ-अशुभ आदि नहीं बनते</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿भावैकांत की मान्यता में दोष</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿प्रागभाव-प्रध्वंसाभाव को न मानने में दोष</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkBlue>﻿अन्योन्याभाव-अत्यंताभाव को न मानने में दोष</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkGreen>﻿अभावैकान्त की मान्यता में दोष</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkBlue>﻿एकांतरूप भावाभाव और अवक्तव्य में दोष</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkGreen>﻿भाव-अभाव आदि निर्दोष कैसे हैं ?</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkBlue>﻿सत् असत् निर्दोष कैसे हैं ?</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkGreen>﻿उभय और अवक्तव्य कथन निर्दोष कैसे हैं ?</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkBlue>﻿भावधर्म अभाव के साथ रहता है</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkGreen>﻿अभाव भाव के साथ रहता है</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿वस्तु भावाभावात्मक है</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿शेष भंग भी नय विवक्षा से बनेंगे</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿वस्तु एक रूप नहीं है</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿प्रत्येक धर्म का अर्थ पृथक् है</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿अन्य धर्मों में भी सप्तभंगी प्रक्रिया करना</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿अद्वैत एकांत में दोष</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿अद्वैत में शुभ-अशुभ आदि द्वैत नहीं बनते </font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿अद्वैत में द्वैत आ जाता है</font></font></a></li>");
document.write("</ul></div>");
